// Downloads the OFL-licensed Cormorant Garamond + Inter woff2 files from
// Google Fonts and generates src/fonts.css, so the app has zero runtime CDN
// dependencies. Usage: node scripts/fetch-fonts.mjs

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const FONT_DIR = path.join(ROOT, 'src', 'assets', 'fonts')
// Chrome UA so the API serves woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Inter:wght@300;400;500;600&display=swap'

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Parse @font-face blocks, keep only the /* latin */ subset of each face.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)]
await mkdir(FONT_DIR, { recursive: true })

let outCss = '/* Generated by scripts/fetch-fonts.mjs — self-hosted OFL fonts */\n'
let count = 0
for (const [, subset, block] of blocks) {
  if (subset !== 'latin') continue
  const family = block.match(/font-family:\s*'([^']+)'/)[1]
  const style = block.match(/font-style:\s*(\w+)/)[1]
  const weight = block.match(/font-weight:\s*(\d+)/)[1]
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)[1]
  const fileName = `${family.replaceAll(' ', '')}-${weight}${style === 'italic' ? 'i' : ''}.woff2`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  await writeFile(path.join(FONT_DIR, fileName), buf)
  outCss += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;src:url('./assets/fonts/${fileName}') format('woff2');}\n`
  count++
}
await writeFile(path.join(ROOT, 'src', 'fonts.css'), outCss)
console.log(`Wrote ${count} font faces to src/assets/fonts and src/fonts.css`)
