// Curated source config for the data pipeline.
// Adding a period or artist later = adding an entry here and re-running `npm run fetch-data`.
// Painting titles are exact en.wikipedia article titles; the pipeline fails loudly on
// titles that don't resolve and rejects any image that is not hosted on Wikimedia
// Commons with a public-domain license.

export const periods = [
  // Keep this array in chronological order — timeline label rows cycle by order.
  {
    id: 'medieval-gothic',
    name: 'Medieval & Gothic',
    wikiTitle: 'Gothic art',
    start: 1200,
    end: 1400,
    color: '#8c6d46',
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    wikiTitle: 'Renaissance art',
    start: 1400,
    end: 1600,
    color: '#c9a227',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    wikiTitle: 'Baroque painting',
    start: 1600,
    end: 1750,
    color: '#a4443c',
  },
  {
    id: 'rococo',
    name: 'Rococo',
    wikiTitle: 'Rococo',
    start: 1720,
    end: 1780,
    color: '#d9a0b4',
  },
  {
    id: 'neoclassicism',
    name: 'Neoclassicism',
    wikiTitle: 'Neoclassicism',
    start: 1770,
    end: 1830,
    color: '#aab3bd',
  },
  {
    id: 'romanticism',
    name: 'Romanticism',
    wikiTitle: 'Romanticism',
    start: 1800,
    end: 1850,
    color: '#7e3b52',
  },
  {
    id: 'realism',
    name: 'Realism',
    wikiTitle: 'Realism (art movement)',
    start: 1848,
    end: 1880,
    color: '#6b7f57',
  },
  {
    id: 'impressionism',
    name: 'Impressionism',
    wikiTitle: 'Impressionism',
    start: 1860,
    end: 1886,
    color: '#5b8bd0',
  },
  {
    id: 'post-impressionism',
    name: 'Post-Impressionism',
    wikiTitle: 'Post-Impressionism',
    start: 1886,
    end: 1905,
    color: '#d0763b',
  },
  {
    id: 'expressionism',
    name: 'Expressionism',
    wikiTitle: 'Expressionism',
    start: 1905,
    end: 1933,
    color: '#d94f30',
  },
  {
    id: 'cubism',
    name: 'Cubism',
    wikiTitle: 'Cubism',
    start: 1907,
    end: 1922,
    color: '#7b6c8f',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    wikiTitle: 'Surrealism',
    start: 1924,
    end: 1955,
    color: '#3fa8a0',
  },
  {
    id: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    wikiTitle: 'Abstract expressionism',
    start: 1943,
    end: 1965,
    color: '#c24b6e',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    wikiTitle: 'Pop art',
    start: 1955,
    end: 1975,
    color: '#38b6e8',
  },
  {
    id: 'contemporary',
    name: 'Contemporary',
    wikiTitle: 'Contemporary art',
    start: 1975,
    end: 2020,
    color: '#9ba53d',
  },
]

export const artists = [
  // ---- Medieval & Gothic ----
  {
    id: 'giotto',
    tier: 'medium',
    periodId: 'medieval-gothic',
    wikiTitle: 'Giotto',
    paintings: [
      'Ognissanti Madonna',
      'Lamentation (The Mourning of Christ)',
      'Stefaneschi Triptych',
      'Badia Polyptych',
      'Saint Francis Receiving the Stigmata (Giotto)',
      'Padua Crucifix',
      "Saint Stephen (Giotto)",
      "Berlin Crucifixion",
      "Life of Christ (Giotto)",
      "Strasbourg Crucifixion",
    ],
  },
  {
    id: 'cimabue',
    tier: 'medium',
    periodId: 'medieval-gothic',
    wikiTitle: 'Cimabue',
    paintings: [
      'Santa Trinita Maestà',
      'Maestà of Santa Maria dei Servi',
      'Gualino Madonna',
      'Castelfiorentino Madonna',
      'Maestà (Cimabue)',
      'The Mocking of Christ (Cimabue)',
      "Crucifix (Cimabue, Santa Croce)",
      "Crucifix (Cimabue, Arezzo)",
      "Diptych of Devotion",
      "The Flagellation of Christ (Cimabue)",
      "Virgin and Child with Two Angels (Cimabue)",
    ],
  },
  {
    id: 'duccio',
    tier: 'small',
    periodId: 'medieval-gothic',
    wikiTitle: 'Duccio',
    paintings: [
      'Maestà (Duccio)',
      'Rucellai Madonna',
      'Madonna and Child (Duccio, Metropolitan)',
      'Crevole Madonna',
      'Madonna with Child and Six Angels',
      'Madonna and Child with Saints Polyptych',
    ],
  },

  {
    id: 'fra-angelico',
    tier: 'large',
    periodId: 'medieval-gothic',
    wikiTitle: 'Fra Angelico',
    paintings: [
      'Annunciation (Fra Angelico, San Marco)',
      'Annunciation of Cortona',
      'San Marco Altarpiece',
      'Coronation of the Virgin (Fra Angelico, Louvre)',
      'The Last Judgment (Fra Angelico, Florence)',
      'Deposition of Christ (Fra Angelico)',
      'Fiesole Altarpiece',
      'Madonna of Humility (Fra Angelico)',
      "Annunciation (Fra Angelico, Madrid)",
      "Coronation of the Virgin (Fra Angelico, Uffizi)",
      "Annunciation of San Giovanni Valdarno",
      "San Pietro Martire Triptych",
      "Perugia Altarpiece",
      "Tabernacle of the Linaioli",
      "Cortona Triptych",
      "Presentation at the Temple (Fra Angelico)",
      "Adoration of the Magi (Fra Angelico and Filippo Lippi)",
      "Adoration of the Magi (San Marco)",
      "Armadio degli Argenti",
      "Croce al Tempio Lamentation",
    ],
  },
  {
    id: 'simone-martini',
    tier: 'medium',
    periodId: 'medieval-gothic',
    wikiTitle: 'Simone Martini',
    paintings: [
      'Annunciation with Saint Margaret and Saint Ansanus',
      'Maestà (Simone Martini)',
      'Guidoriccio da Fogliano at the Siege of Montemassi',
      'Saint Louis of Toulouse Crowning His Brother Robert of Anjou',
      'Blessed Agostino Novello Triptych',
      'Orsini Polyptych',
      'Saint Catherine of Alexandria Polyptych',
      "San Martino Chapel",
    ],
  },

  // ---- Renaissance ----
  {
    id: 'leonardo-da-vinci',
    tier: 'medium',
    periodId: 'renaissance',
    wikiTitle: 'Leonardo da Vinci',
    paintings: [
      'Mona Lisa',
      'The Last Supper (Leonardo)',
      'Lady with an Ermine',
      "Ginevra de' Benci",
      'Virgin of the Rocks',
      'Annunciation (Leonardo)',
      'Saint John the Baptist (Leonardo)',
      'La Belle Ferronnière',
      "The Virgin and Child with Saint Anne (Leonardo)",
      "Benois Madonna",
      "Adoration of the Magi (Leonardo)",
      "Altarpiece in the Chapel of the Immaculate Conception",
      "Colored Mona Lisa",
      "Crown Hotel (Mona Lisa Black Background)",
      "Isleworth Mona Lisa",
      "L.H.O.O.Q.",
      "La Joconde nue",
      "La Scapigliata",
      "Leda and the Swan (Leonardo)",
      "Madonna and Child with the Infant Saint John the Baptist (Leonardo)",
    ],
  },
  {
    id: 'michelangelo',
    tier: 'medium',
    periodId: 'renaissance',
    wikiTitle: 'Michelangelo',
    paintings: [
      'The Creation of Adam',
      'The Last Judgment (Michelangelo)',
      'Doni Tondo',
      'The Entombment (Michelangelo)',
      'Manchester Madonna',
      'The Torment of Saint Anthony (Michelangelo)',
      "Sistine Chapel ceiling",
      "Battle of Cascina (Michelangelo)",
      "Leda and the Swan (Michelangelo)",
      "The Conversion of Saul (Michelangelo)",
      "The Crucifixion of Saint Peter (Michelangelo)",
    ],
  },
  {
    id: 'raphael',
    tier: 'large',
    periodId: 'renaissance',
    wikiTitle: 'Raphael',
    paintings: [
      'The School of Athens',
      'Sistine Madonna',
      'Transfiguration (Raphael)',
      'The Marriage of the Virgin (Raphael)',
      'Saint George and the Dragon (Raphael)',
      'La Fornarina',
      'Portrait of Baldassare Castiglione',
      'Madonna of the Goldfinch',
      "Raphael Rooms",
      "Disputation of the Holy Sacrament",
      "Galatea (Raphael)",
      "Alba Madonna",
      "La velata",
      "Madonna del Granduca",
      "La belle jardinière",
      "Madonna della Seggiola",
      "Self-portrait (Raphael)",
      "Vision of a Knight (Raphael)",
      "Oddi Altarpiece (Raphael)",
    ],
  },

  {
    id: 'titian',
    tier: 'large',
    periodId: 'renaissance',
    wikiTitle: 'Titian',
    paintings: [
      'Venus of Urbino',
      'Bacchus and Ariadne',
      'Sacred and Profane Love',
      'Assumption of the Virgin (Titian)',
      'Diana and Actaeon (Titian)',
      'Equestrian Portrait of Charles V',
      'Pietà (Titian)',
      'Penitent Magdalene (Titian, 1550)',
      "Sleeping Venus (Giorgione)",
      "Flora (Titian)",
      "The Feast of the Gods",
      "Allegory of Prudence",
      "The Rape of Europa (Titian)",
      "Woman with a Mirror",
      "La Bella",
      "Pope Paul III and His Grandsons",
      "Penitent Magdalene (Titian, 1565)",
      "La Schiavona",
      "Pastoral Concert",
      "Tarquin and Lucretia",
    ],
  },
  {
    id: 'sandro-botticelli',
    tier: 'large',
    periodId: 'renaissance',
    wikiTitle: 'Sandro Botticelli',
    paintings: [
      'The Birth of Venus',
      'Primavera (Botticelli)',
      'Venus and Mars (Botticelli)',
      'The Mystical Nativity',
      'Madonna of the Magnificat',
      'Pallas and the Centaur',
      'Adoration of the Magi (Botticelli, 1475)',
      'Cestello Annunciation',
      "Adoration of the Magi (Botticelli)",
      "Calumny of Apelles",
      "Portrait of a Young Woman (Botticelli, Frankfurt)",
      "Youth of Moses",
      "Madonna of the Pomegranate",
      "Punishment of the Sons of Korah",
      "Temptations of Christ (Botticelli)",
      "Portrait of a Man with a Medal of Cosimo the Elder",
      "The Story of Lucretia (Botticelli)",
      "Virgin and Child with an Angel (Botticelli, Florence)",
      "Bardi Madonna",
      "Portrait of a Young Man holding a Roundel",
    ],
  },
  {
    id: 'jan-van-eyck',
    tier: 'large',
    periodId: 'renaissance',
    wikiTitle: 'Jan van Eyck',
    paintings: [
      'Arnolfini Portrait',
      'Ghent Altarpiece',
      'Madonna of Chancellor Rolin',
      'Madonna in the Church',
      'Virgin and Child with Canon van der Paele',
      'Annunciation (van Eyck, Washington)',
      'Dresden Triptych',
      'Lucca Madonna',
      "Portrait of a Man (Self Portrait?)",
      "Ince Hall Madonna",
      "Annunciation (van Eyck, Madrid)",
      "Crucifixion and Last Judgement diptych",
      "Léal Souvenir",
      "Madonna at the Fountain",
      "Madonna of Jan Vos",
      "Madonna of Nicolas van Maelbeke",
      "Portrait of a Man with a Blue Chaperon",
      "Portrait of a Man with Carnation",
      "Portrait of Baudouin de Lannoy",
      "Portrait of Cardinal Niccolò Albergati",
    ],
  },

  // ---- Baroque ----
  {
    id: 'caravaggio',
    tier: 'large',
    periodId: 'baroque',
    wikiTitle: 'Caravaggio',
    paintings: [
      'The Calling of Saint Matthew',
      'Judith Beheading Holofernes (Caravaggio)',
      'David with the Head of Goliath (Caravaggio, Rome)',
      'Bacchus (Caravaggio)',
      'Basket of Fruit (Caravaggio)',
      'Supper at Emmaus (Caravaggio, London)',
      'The Entombment of Christ (Caravaggio)',
      'The Cardsharps',
      "Amor Vincit Omnia (Caravaggio)",
      "Medusa (Caravaggio)",
      "Young Sick Bacchus",
      "Death of the Virgin (Caravaggio)",
      "The Fortune Teller (Caravaggio)",
      "Boy with a Basket of Fruit",
      "Crucifixion of Saint Peter (Caravaggio)",
      "The Martyrdom of Saint Matthew (Caravaggio)",
      "The Inspiration of Saint Matthew",
      "The Taking of Christ (Caravaggio)",
      "Boy Bitten by a Lizard",
      "Rest on the Flight into Egypt (Caravaggio)",
    ],
  },
  {
    id: 'rembrandt',
    tier: 'large',
    periodId: 'baroque',
    wikiTitle: 'Rembrandt',
    paintings: [
      'The Night Watch',
      'The Anatomy Lesson of Dr. Nicolaes Tulp',
      'The Storm on the Sea of Galilee',
      'The Jewish Bride',
      "Belshazzar's Feast (Rembrandt)",
      'The Return of the Prodigal Son (Rembrandt)',
      'Aristotle with a Bust of Homer',
      'Self-Portrait with Two Circles',
      "Danaë (Rembrandt)",
      "Syndics of the Drapers' Guild",
      "Bathsheba at Her Bath (Rembrandt)",
      "Moses Breaking the Tablets of the Law",
      "The Abduction of Europa (Rembrandt)",
      "The Prodigal Son in the Brothel",
      "Flora (Rembrandt, Hermitage)",
      "Judith at the Banquet of Holofernes",
      "The Stoning of Saint Stephen",
      "Balaam and the Ass",
      "Andromeda Chained to the Rocks",
      "Jacob Blessing the Sons of Joseph (Rembrandt)",
    ],
  },
  {
    id: 'johannes-vermeer',
    tier: 'large',
    periodId: 'baroque',
    wikiTitle: 'Johannes Vermeer',
    paintings: [
      'Girl with a Pearl Earring',
      'The Milkmaid (Vermeer)',
      'View of Delft',
      'The Art of Painting',
      'The Astronomer (Vermeer)',
      'The Geographer',
      'The Little Street',
      'Girl Reading a Letter at an Open Window',
      "The Concert (Vermeer)",
      "The Music Lesson",
      "The Lacemaker (Vermeer)",
      "Christ in the House of Martha and Mary (Vermeer)",
      "Woman with a Water Jug",
      "The Wine Glass",
      "Lady Writing a Letter with her Maid",
      "The Allegory of Faith",
      "The Love Letter (Vermeer)",
      "Girl Interrupted at Her Music",
      "Study of a Young Woman",
    ],
  },

  {
    id: 'peter-paul-rubens',
    tier: 'large',
    periodId: 'baroque',
    wikiTitle: 'Peter Paul Rubens',
    paintings: [
      'The Descent from the Cross (Rubens, 1612–1614)',
      'The Elevation of the Cross (Rubens)',
      'Massacre of the Innocents (Rubens)',
      'Samson and Delilah (Rubens)',
      'The Garden of Love (Rubens)',
      "Daniel in the Lions' Den (Rubens)",
      'The Hippopotamus and Crocodile Hunt',
      'The Fall of the Damned',
      "The Rape of the Daughters of Leucippus",
      "Honeysuckle Bower",
      "The Three Graces (Rubens, Madrid)",
      "Romulus and Remus (Rubens)",
      "Medusa (Rubens)",
      "The Judgement of Paris (Rubens)",
      "Marie de' Medici cycle",
      "The Fall of Man (Rubens)",
      "The Birth of the Milky Way",
      "The Garden of Eden with the Fall of Man",
      "Assumption of the Virgin (Rubens, Antwerp)",
      "Saturn (Rubens)",
    ],
  },
  {
    id: 'diego-velazquez',
    tier: 'large',
    periodId: 'baroque',
    wikiTitle: 'Diego Velázquez',
    paintings: [
      'Las Meninas',
      'The Surrender of Breda',
      'Rokeby Venus',
      'Portrait of Innocent X',
      'The Triumph of Bacchus',
      'Apollo in the Forge of Vulcan',
      'Old Woman Frying Eggs',
      'The Waterseller of Seville',
      "The Lunch (Velázquez)",
      "The Farmers' Lunch",
      "Adoration of the Magi (Velázquez)",
      "Three Musicians (Velázquez)",
      "Christ in the House of Martha and Mary (Velázquez)",
      "Saint Paul (Velázquez)",
      "The Kitchen Maid",
      "Female Figure (Velázquez)",
      "Prince Baltasar Carlos in the Riding School",
    ],
  },
  {
    id: 'artemisia-gentileschi',
    tier: 'large',
    periodId: 'baroque',
    wikiTitle: 'Artemisia Gentileschi',
    paintings: [
      'Judith Slaying Holofernes (Artemisia Gentileschi, Florence)',
      'Judith Slaying Holofernes (Artemisia Gentileschi, Naples)',
      'Self-Portrait as the Allegory of Painting',
      'Susanna and the Elders (Artemisia Gentileschi, Pommersfelden)',
      'Judith and Her Maidservant (Artemisia Gentileschi, Florence)',
      'Self-Portrait as Saint Catherine of Alexandria',
      'Lucretia (Artemisia Gentileschi, Milan)',
      'Danaë (Artemisia Gentileschi)',
      "Esther Before Ahasuerus (Artemisia Gentileschi)",
      "Jael and Sisera (Artemisia Gentileschi)",
      "Mary Magdalene (Artemisia Gentileschi)",
      "Self-Portrait as a Female Martyr",
      "Self-Portrait as a Lute Player",
      "Adoration of the Magi (Artemisia Gentileschi)",
      "Cleopatra (Artemisia Gentileschi, Ferrara)",
      "Lot and His Daughters (Artemisia Gentileschi)",
      "Lucretia (Artemisia Gentileschi, Potsdam)",
      "Madonna and Child (Artemisia Gentileschi)",
      "Saint Cecilia (Artemisia Gentileschi)",
      "Allegory of Painting (Le Mans)",
    ],
  },

  // ---- Rococo ----
  {
    id: 'antoine-watteau',
    tier: 'large',
    periodId: 'rococo',
    wikiTitle: 'Antoine Watteau',
    paintings: [
      'The Embarkation for Cythera',
      'Pierrot (Watteau)',
      "L'Enseigne de Gersaint",
      'Mezzetino (Watteau)',
      'The Embarrassing Proposal',
      'Fêtes Vénitiennes',
      "L'Indifférent",
      'The Two Cousins',
      "Jupiter and Antiope (Watteau)",
      "Actors of the Comédie-Française",
      "The Chord (painting)",
      "The Faux Pas",
      "Cupid Disarmed (Watteau)",
      "Pastoral Pleasure",
      "The Country Dance",
      "The Dreamer (painting)",
      "The Surprise (Watteau)",
      "The Worried Lover",
      "La Boudeuse (painting)",
      "Marriage Contract and Country Dancing",
    ],
  },
  {
    id: 'francois-boucher',
    tier: 'large',
    periodId: 'rococo',
    wikiTitle: 'François Boucher',
    paintings: [
      'The Toilet of Venus (Boucher)',
      'Portrait of Madame de Pompadour',
      'The Blonde Odalisque',
      'Lovers in a Park',
      'Pompadour at Her Toilette',
      'The Brunette Odalisque',
      "Diana Bathing (Boucher)",
      "The Birth of Venus (Boucher)",
      "The Setting of the Sun",
      "The Triumph of Venus",
      "Aurora and Cephalus (Boucher)",
      "Hercules and Omphale (Boucher)",
      "Jupiter and Callisto (Boucher, 1744)",
      "Pastoral with a Couple near a Fountain",
      "Venus Consoling Love",
      "Fishing (Boucher)",
      "Landscape near Beauvais",
      "The Rising of the Sun",
      "Jupiter and Callisto (Boucher, 1759)",
      "Diana Returning from the Hunt",
    ],
  },
  {
    id: 'jean-honore-fragonard',
    tier: 'large',
    periodId: 'rococo',
    wikiTitle: 'Jean-Honoré Fragonard',
    paintings: [
      // article's lead image is a CC BY-SA re-photograph; use the PD-Art scan
      { title: 'The Swing (Fragonard)', imageFile: 'Jean-Honoré Fragonard - The Swing - Google Art Project.jpg' },
      'A Young Girl Reading',
      'The Bolt (Fragonard)',
      'The Stolen Kiss (painting)',
      'Blind Man\'s Buff (Fragonard, 1775–1780)',
      'The See-Saw (Fragonard, Madrid)',
      'The Music Lesson (Fragonard)',
      'Coresus Sacrificing Himself to Save Callirhoe',
      "Blind Man's Bluff (Fragonard, 1750)",
      "The Birth of Venus (Fragonard)",
      "Jeroboam Sacrificing to Idols",
      "The New Model",
      "La Gimblette",
      "The Raised Chemise",
      "Jean-Claude Richard, Abbot of Saint-Non, Dressed à l'Espagnole",
      "Psyche Showing Her Sisters Her Gifts from Cupid",
      "The Visit to the Nursery",
      "The Storm (Fragonard)",
      "The Woman with a Dog",
      "Adoration of the Shepherds (Fragonard)",
    ],
  },

  {
    id: 'jean-baptiste-simeon-chardin',
    tier: 'medium',
    periodId: 'rococo',
    wikiTitle: 'Jean-Baptiste-Siméon Chardin',
    paintings: [
      'The Ray (Chardin)',
      'Saying Grace (Chardin)',
      'Soap Bubbles (Chardin)',
      'The House of Cards',
      'Boy with a Spinning-Top',
      'The Laundress (Chardin)',
      'Girl with a Racquet',
      'The Kitchen Maid (Chardin)',
      "The Buffet (Chardin)",
      "The Attributes of Music, the Arts and the Sciences",
      "The Attributes of Civilian and Military Music",
    ],
  },

  // ---- Neoclassicism ----
  {
    id: 'jacques-louis-david',
    tier: 'large',
    periodId: 'neoclassicism',
    wikiTitle: 'Jacques-Louis David',
    paintings: [
      'Oath of the Horatii',
      'The Death of Marat',
      'The Coronation of Napoleon',
      'Napoleon Crossing the Alps',
      'The Death of Socrates',
      'The Lictors Bring to Brutus the Bodies of His Sons',
      'Belisarius Begging for Alms',
      'Leonidas at Thermopylae',
      "The Intervention of the Sabine Women",
      "The Emperor Napoleon in His Study at the Tuileries",
      "Mars Being Disarmed by Venus",
      "Portrait of Madame Récamier",
      "Erasistratus Discovering the Cause of Antiochus' Disease",
      "Andromache Mourning Hector",
      "The Death of Seneca",
      "Portrait of Antoine and Marie-Anne Lavoisier",
      "The Loves of Paris and Helen",
      "Love and Psyche (David)",
      "The Anger of Achilles",
      "The Distribution of the Eagle Standards",
    ],
  },
  {
    id: 'jean-auguste-dominique-ingres',
    tier: 'large',
    periodId: 'neoclassicism',
    wikiTitle: 'Jean-Auguste-Dominique Ingres',
    paintings: [
      'Grande Odalisque',
      'The Turkish Bath',
      'The Valpinçon Bather',
      'The Apotheosis of Homer (Ingres)',
      'Jupiter and Thetis',
      'Oedipus and the Sphinx (Ingres)',
      'The Source (Ingres)',
      'Joan of Arc at the Coronation of Charles VII',
      "Napoleon I on His Imperial Throne",
      "Portrait of Madame Moitessier",
      "Venus Anadyomene (Ingres)",
      "Portrait of Monsieur Bertin",
      "Mademoiselle Caroline Rivière",
      "The Ambassadors of Agamemnon in the tent of Achilles",
      "The Princesse de Broglie",
      "Odalisque with Slave",
      "Portrait of Comtesse d'Haussonville",
      "The Death of Leonardo da Vinci",
      "The Illness of Antiochus",
      "Portrait of Madame de Senonnes",
    ],
  },
  {
    id: 'elisabeth-vigee-le-brun',
    tier: 'large',
    periodId: 'neoclassicism',
    wikiTitle: 'Élisabeth Vigée Le Brun',
    paintings: [
      'Self-Portrait in a Straw Hat',
      'Marie Antoinette and Her Children',
      'Marie Antoinette with a Rose',
      'Self-Portrait with Julie (Maternal Tenderness)',
      'Lady Hamilton as a Bacchante',
      'Portrait of Countess Golovina',
      'Madame de Staël as Corinne at Cape Miseno',
      'Portrait of Hubert Robert',
      "Self-Portrait with Julie (Self-Portrait à la Grecque)",
      "Portrait of Princess Maria Christina",
      "Comtesse de la Châtre",
      "Portrait of Countess Yekaterina Skavronskaya",
      "Self-Portrait Painting Marie Antoinette",
      "Peace Bringing Back Abundance",
      "Portrait of Charles Alexandre de Calonne",
      "Portrait of Countess Yekaterina von Engelhardt",
      "Anne Pitt as Hebe",
      "Portrait of Joseph Vernet",
      "Portrait of Madame Perregaux",
      "Portrait of Muhammad Dervish Khan",
    ],
  },

  {
    id: 'honore-daumier',
    tier: 'small',
    periodId: 'realism',
    wikiTitle: 'Honoré Daumier',
    paintings: [
      'The Third-Class Carriage',
      'Don Quixote and Sancho Panza (Daumier)',
      'The Laundress (Daumier)',
      'The Chess Players (Daumier)',
      'Ecce Homo (Daumier)',
      'The Emigrants (Daumier)',
      'The Republic (Daumier)',
      'Melodrama (Daumier)',
    ],
  },

  // ---- Impressionism ----
  {
    id: 'claude-monet',
    tier: 'large',
    periodId: 'impressionism',
    wikiTitle: 'Claude Monet',
    paintings: [
      'Impression, Sunrise',
      'Woman with a Parasol – Madame Monet and Her Son',
      'The Magpie (Monet)',
      'Haystacks (Monet series)',
      'Rouen Cathedral (Monet series)',
      'Water Lilies (Monet series)',
      'Garden at Sainte-Adresse',
      'La Grenouillère (Monet)',
      "Women in the Garden",
      "Woman in the Garden",
      "Le Déjeuner sur l'herbe (Monet, Paris)",
      "La Japonaise (painting)",
      "Regatta at Sainte-Adresse (Monet)",
      "Regatta at Argenteuil",
      "The Artist's Garden at Giverny",
      "Gare Saint-Lazare (Monet series)",
      "Poplars (Monet series)",
      "San Giorgio Maggiore at Dusk",
      "Springtime (Claude Monet)",
      "Beach in Pourville",
    ],
  },
  {
    id: 'pierre-auguste-renoir',
    tier: 'large',
    periodId: 'impressionism',
    wikiTitle: 'Pierre-Auguste Renoir',
    paintings: [
      'Bal du moulin de la Galette',
      'Luncheon of the Boating Party',
      'Dance at Bougival',
      'Le Pont-Neuf (Renoir)',
      'The Swing (Renoir)',
      'Girls at the Piano',
      'Dance in the City',
      'Pink and Blue (Renoir)',
      "Les Grandes Baigneuses (Renoir)",
      "La Loge",
      "The Umbrellas (Renoir)",
      "Two Sisters (On the Terrace)",
      "Dance in the Country",
      "In Summer (Renoir)",
      "Lise with a Parasol",
      "Portrait of Irène Cahen d'Anvers",
      "La Grenouillère (Renoir)",
      "La Promenade (Renoir)",
      "The Day Dream (Renoir)",
      "La Parisienne (Renoir)",
    ],
  },
  {
    id: 'edgar-degas',
    tier: 'large',
    periodId: 'impressionism',
    wikiTitle: 'Edgar Degas',
    paintings: [
      "L'Absinthe",
      "The Ballet Class (Degas, Musée d'Orsay)",
      'The Dance Class (Degas, Metropolitan Museum of Art)',
      'A Cotton Office in New Orleans',
      'Miss La La at the Cirque Fernando',
      'Place de la Concorde (Degas)',
      'The Orchestra at the Opera',
      'Young Spartans Exercising',
      "The Bellelli Family",
      "Interior (Degas)",
      "Count Lepic and His Daughters",
      "The Millinery Shop",
      "The Dancing Class",
      "Before the Race",
      "Lorenzo Pagans and Auguste de Gas",
      "The Collector of Prints (Degas)",
      "Ballerina Posing for a Photographer",
      "Portraits at the Stock Exchange",
      "The Dance Lesson",
      "Dance Class at the Opera",
    ],
  },

  // Mengs has no painting articles on en.wikipedia; West and Kauffman carry
  // the period's depth instead.
  {
    id: 'benjamin-west',
    tier: 'large',
    periodId: 'neoclassicism',
    wikiTitle: 'Benjamin West',
    paintings: [
      'The Death of General Wolfe',
      'Death on the Pale Horse',
      'Benjamin Franklin Drawing Electricity from the Sky',
      "Penn's Treaty with the Indians",
      'The Death of Nelson (West painting)',
      'The Battle of La Hogue',
      'The Departure of Regulus',
      'Agrippina Landing at Brundisium with the Ashes of Germanicus',
      "General Johnson Saving a Wounded French Officer from the Tomahawk of a North American Indian",
      "Treaty of Paris (painting)",
      "Portrait of Dr Richard Price",
      "Colonel Guy Johnson and Karonghyontye (Captain David Hill)",
      "Edward III Crossing the Somme",
      "Portrait of George III (West)",
      "Portrait of Queen Charlotte (West)",
      "Queen Philippa at the Battle of Neville's Cross",
      "The Institution of the Order of the Garter",
      "The Oath of Hannibal",
      "Alexander III of Scotland Rescued from the Fury of a Stag by the Intrepidity of Colin Fitzgerald",
      "Alfred the Great Dividing His Loaf with a Pilgrim",
    ],
  },
  {
    id: 'angelica-kauffman',
    tier: 'large',
    periodId: 'neoclassicism',
    wikiTitle: 'Angelica Kauffman',
    portraitFile: 'Angelica Kauffmann, Self-Portrait as the Muse of Painting, 1787.jpg',
    paintings: [
      'Ariadne Abandoned by Theseus',
      'Penelope at Her Loom',
      'Cupid and the Graces',
      'Zeuxis Selecting Models for His Painting of Helen of Troy',
      'Virgil Reading the Aeneid to Augustus and Octavia',
      'The Sorrow of Telemachus',
      'Vortigern and Rowena (painting)',
      'Sappho Inspired by Love',
      "Ferdinand I and His Family",
      "Hector Summoning Paris to Battle",
      "Portrait of Winckelmann",
      "Telemachus and the Nymphs of Calypso",
      "The Parting of Abelard and Heloise",
      "Venus Persuading Helen to Love Paris",
      "Jupiter Disguised as Diana Seducing Callisto",
      "Self-Portrait (Kauffman, 1784)",
      "Bacchantes (Kauffman)",
      "Portrait of David Garrick (Kauffman)",
      "Portrait of Ludwig, Crown Prince of Bavaria",
      "Armida in Vain Endeavours with Her Entreaties to Prevent Rinaldo's Departure",
    ],
  },

  // ---- Romanticism ----
  {
    id: 'francisco-goya',
    tier: 'large',
    periodId: 'romanticism',
    wikiTitle: 'Francisco Goya',
    paintings: [
      'The Third of May 1808',
      'The Second of May 1808',
      'Saturn Devouring His Son',
      'La maja desnuda',
      'La maja vestida',
      'Charles IV of Spain and His Family',
      "Witches' Sabbath (Goya, 1798)",
      'The Dog (Goya)',
      "Black Paintings",
      "Manuel Osorio Manrique de Zúñiga",
      "Portrait of Doña Isabel de Porcel",
      "Portrait of the Marchioness of Santa Cruz",
      "Self-Portrait with Dr Arrieta",
      "The Burial of the Sardine",
      "The Countess of Chinchon",
      "Asmodea",
      "The Family of the Infante Don Luis",
      "The Inquisition Tribunal",
      "The Madhouse",
      "Truth, Time and History",
    ],
  },
  {
    id: 'caspar-david-friedrich',
    tier: 'large',
    periodId: 'romanticism',
    wikiTitle: 'Caspar David Friedrich',
    paintings: [
      'Wanderer above the Sea of Fog',
      'The Sea of Ice',
      'The Monk by the Sea',
      'The Abbey in the Oakwood',
      'Chalk Cliffs on Rügen',
      'The Stages of Life',
      'Two Men Contemplating the Moon',
      'Cross in the Mountains',
      "Mountain Landscape with Rainbow",
      "The Lonely Tree",
      "The Tree of Crows",
      "The Watzmann",
      "Woman at a Window",
      "The Port of Greifswald",
      "Cairn in Snow",
      "Evening (painting)",
      "Moonrise by the Sea",
      "Cabin in the Snow",
      "Morning on the Riesengebirge",
      "Neubrandenburg (painting)",
    ],
  },
  {
    id: 'eugene-delacroix',
    tier: 'large',
    periodId: 'romanticism',
    wikiTitle: 'Eugène Delacroix',
    paintings: [
      'Liberty Leading the People',
      'The Death of Sardanapalus',
      'The Massacre at Chios',
      'The Barque of Dante',
      'Women of Algiers',
      'Entry of the Crusaders in Constantinople',
      'Greece on the Ruins of Missolonghi',
      'The Lion Hunt (Delacroix)',
      "Orphan Girl at the Cemetery",
      "Jewish Wedding in Morocco",
      "Portrait of Frédéric Chopin and George Sand",
      "Woman Stroking a Parrot",
      "Last Words of the Emperor Marcus Aurelius",
      "A Young Tiger Playing with Its Mother",
      "Mademoiselle Rose",
      "The Abduction of Rebecca",
      "The Battle of Taillebourg, 21 July 1242",
      "The Bride of Abydos (Delacroix)",
      "The Sultan of Morocco",
      "Christ on the Cross (Delacroix)",
    ],
  },
  {
    id: 'jmw-turner',
    tier: 'large',
    periodId: 'romanticism',
    wikiTitle: 'J. M. W. Turner',
    paintings: [
      'The Fighting Temeraire',
      'Rain, Steam and Speed – The Great Western Railway',
      'The Slave Ship',
      "Snow Storm: Steam-Boat off a Harbour's Mouth",
      'The Burning of the Houses of Lords and Commons',
      'Dido building Carthage',
      'Ulysses Deriding Polyphemus',
      'Norham Castle, Sunrise',
      "The Battle of Trafalgar (Turner)",
      "Snow Storm: Hannibal and his Army Crossing the Alps",
      "Dolbadarn Castle (Turner)",
      "Fishermen at Sea",
      "Sunrise with Sea Monsters",
      "Light and Colour (Goethe's Theory) – The Morning after the Deluge – Moses Writing the Book of Genesis",
      "Modern Rome – Campo Vaccino",
      "The Golden Bough (painting)",
      "Chichester Canal (painting)",
      "Rome, From Mount Aventine",
      "Rome, from the Vatican",
      "The Fifth Plague of Egypt",
    ],
  },

  {
    id: 'theodore-gericault',
    tier: 'medium',
    periodId: 'romanticism',
    wikiTitle: 'Théodore Géricault',
    paintings: [
      'The Raft of the Medusa',
      'The Charging Chasseur',
      'The Wounded Cuirassier',
      'The 1821 Derby at Epsom',
      'Portrait of a Kleptomaniac',
      'The Woman with a Gambling Mania',
      'Monomaniac of Envy',
      'Evening: Landscape with an Aqueduct',
      "The Melancholic Man",
      "A Charge of Cuirassiers",
    ],
  },
  {
    id: 'william-blake',
    tier: 'small',
    periodId: 'romanticism',
    wikiTitle: 'William Blake',
    paintings: [
      'The Ghost of a Flea',
      'Newton (Blake)',
      'The Ancient of Days',
      'Nebuchadnezzar (Blake)',
      'The Great Red Dragon paintings',
    ],
  },

  // ---- Realism ----
  {
    id: 'gustave-courbet',
    tier: 'large',
    periodId: 'realism',
    wikiTitle: 'Gustave Courbet',
    paintings: [
      'A Burial at Ornans',
      'The Stone Breakers',
      "The Painter's Studio",
      'Le Désespéré',
      'The Meeting (Courbet)',
      'Self-Portrait with a Black Dog',
      'The Wheat Sifters',
      'The Wave (Courbet)',
      "L'Origine du monde",
      "Le Sommeil",
      "Woman with a Parrot (Courbet)",
      "The Woman in the Waves",
      "Young Ladies Beside the Seine (Summer)",
      "The Source (Courbet)",
      "The Wounded Man (painting)",
      "Femme nue couchée",
      "Killing a Deer",
      "The Bathers (Courbet)",
      "The Bacchante (Courbet)",
      "After Dinner at Ornans",
    ],
  },
  {
    id: 'jean-francois-millet',
    tier: 'medium',
    periodId: 'realism',
    wikiTitle: 'Jean-François Millet',
    paintings: [
      'The Gleaners',
      'The Angelus (painting)',
      'The Sower (Millet)',
      'Man with a Hoe',
      'Shepherdess with her Flock',
      'The Winnower (Millet)',
      'The Potato Harvest',
      'Starry Night (Millet)',
      "Haystacks: Autumn",
      "Shepherdess Seated on a Rock",
      "The Beakful",
      "Peasant with a Wheelbarrow",
      "Peasant Women with Brushwood",
    ],
  },
  {
    id: 'edouard-manet',
    tier: 'large',
    periodId: 'realism',
    wikiTitle: 'Édouard Manet',
    paintings: [
      'Olympia (Manet)',
      "Le Déjeuner sur l'herbe",
      'A Bar at the Folies-Bergère',
      'The Balcony (Manet)',
      'Music in the Tuileries',
      'The Railway',
      'The Old Musician',
      'The Execution of Emperor Maximilian',
      "The Fifer",
      "Nana (Manet)",
      "Berthe Morisot with a Bouquet of Violets",
      "Plum Brandy",
      "Portrait of Emile Zola",
      "Spring (Manet)",
      "Le Suicidé",
      "The Absinthe Drinker (Manet)",
      "The Spanish Singer",
      "La Nymphe surprise",
      "In the Conservatory",
      "Boating (Manet)",
    ],
  },

  {
    id: 'berthe-morisot',
    tier: 'medium',
    periodId: 'impressionism',
    wikiTitle: 'Berthe Morisot',
    paintings: [
      'The Cradle (Morisot)',
      "Summer's Day",
      'Eugène Manet on the Isle of Wight',
      'In the Dining Room',
      'Woman at her Toilette',
      'The Mother and Sister of the Artist',
      'The Harbor at Lorient',
      'The Psyche Mirror',
      "In a Park",
      "La Petite Niçoise",
      "Young Girl in a Park",
    ],
  },
  {
    id: 'mary-cassatt',
    tier: 'large',
    periodId: 'impressionism',
    wikiTitle: 'Mary Cassatt',
    paintings: [
      "The Child's Bath",
      'The Boating Party',
      'Little Girl in a Blue Armchair',
      'The Cup of Tea',
      'In the Loge',
      'Lady at the Tea Table',
      'Young Mother Sewing (Mary Cassatt)',
      'The Tea',
      "Woman with a Pearl Necklace in a Loge",
      "Girl Arranging Her Hair",
      "Mother and Child (Cassatt)",
      "Woman with a Sunflower",
      "A Woman and a Girl Driving",
      "Lilacs in a Window",
      "Lydia Crocheting in the Garden at Marly",
      "Portrait of the Artist (Mary Cassatt)",
    ],
  },
  {
    id: 'alfred-sisley',
    tier: 'large',
    periodId: 'impressionism',
    wikiTitle: 'Alfred Sisley',
    paintings: [
      'The Bridge at Villeneuve-la-Garenne',
      'Flooding at Port-Marly',
      'Regatta at Molesey near Hampton Court',
      'The Forge at Marly-le-Roi',
      'Frost in Louveciennes',
      'Place du Chenil in Marly, Snow Effect',
      'The Seine at Bougival',
      'Under Hampton Court Bridge',
      "Avenue of Chestnut Trees at La Celle-Saint-Cloud",
      "The Seine at Port-Marly, Piles of Sand",
      "The Banks of the Oise",
      "View of the Canal Saint-Martin",
      "Chemin de la Machine, Louveciennes",
      "The Small Meadows in Spring, By",
      "A Street in Marly",
      "Avenue of Poplars near Moret-sur-Loing",
      "Ferry to the Ile-de-la-Loge – Flood",
      "Rue de la Chaussée in Argenteuil",
      "The Canal du Loing (painting)",
      "The Seine at Argenteuil (Sisley)",
    ],
  },

  // ---- Post-Impressionism ----
  {
    id: 'vincent-van-gogh',
    tier: 'large',
    periodId: 'post-impressionism',
    wikiTitle: 'Vincent van Gogh',
    paintings: [
      'The Starry Night',
      'Sunflowers (Van Gogh series)',
      'Café Terrace at Night',
      'The Potato Eaters',
      'Wheatfield with Crows',
      'Self-Portrait with Bandaged Ear',
      'Irises (painting)',
      'Almond Blossoms',
      "Portrait of Dr. Gachet",
      "Bedroom in Arles",
      "Starry Night Over the Rhône",
      "The Night Café",
      "The Church at Auvers",
      "The Red Vineyard",
      "The Yellow House",
      "Sunset at Montmajour",
      "At Eternity's Gate",
      "Portrait of Père Tanguy",
      "Skull of a Skeleton with Burning Cigarette",
      "The Parsonage Garden at Nuenen",
    ],
  },
  {
    id: 'paul-cezanne',
    tier: 'large',
    periodId: 'post-impressionism',
    wikiTitle: 'Paul Cézanne',
    paintings: [
      'The Card Players',
      'The Basket of Apples',
      'Mont Sainte-Victoire (Cézanne)',
      'The Bathers (Cézanne)',
      'Pyramid of Skulls',
      "The Hanged Man's House",
      'A Modern Olympia',
      'Still Life with Apples and Oranges',
      "Pierrot and Harlequin",
      "The Boy in the Red Vest",
      "Lady in Blue (Cézanne)",
      "Mont Sainte-Victoire seen from Bellevue",
      "Rideau, Cruchon et Compotier",
      "The Overture to Tannhäuser",
      "House in Provence",
      "Mont Sainte-Victoire with Large Pine",
      "Forest (painting)",
      "Pont de Maincy",
      "Still Life with Peaches and Pears",
      "Portrait of Ambroise Vollard (Cézanne)",
    ],
  },
  {
    id: 'paul-gauguin',
    tier: 'large',
    periodId: 'post-impressionism',
    wikiTitle: 'Paul Gauguin',
    paintings: [
      'Where Do We Come From? What Are We? Where Are We Going?',
      'The Yellow Christ',
      'Vision After the Sermon',
      'When Will You Marry?',
      'Spirit of the Dead Watching',
      'Two Tahitian Women',
      'Ia Orana Maria',
      'Nevermore (Gauguin)',
      "Tahitian Women on the Beach",
      "The Green Christ",
      "Aha Oe Feii?",
      "Vincent van Gogh Painting Sunflowers",
      "Study of a Nude",
      "Tahitian Woman with a Flower",
      "Arearea",
      "Fatata te Miti (By the Sea)",
      "Self-Portrait in a Hat",
      "The Beautiful Angel",
      "Vairumati",
      "Self-Portrait with the Yellow Christ",
    ],
  },

  {
    id: 'georges-seurat',
    tier: 'medium',
    periodId: 'post-impressionism',
    wikiTitle: 'Georges Seurat',
    paintings: [
      'A Sunday Afternoon on the Island of La Grande Jatte',
      'Bathers at Asnières',
      'The Circus (Seurat)',
      'Le Chahut',
      'Parade de cirque',
      'Models (painting)',
      'Young Woman Powdering Herself (Seurat)',
      'The Channel of Gravelines, Petit Fort Philippe',
      "The Lighthouse at Honfleur",
    ],
  },
  {
    id: 'henri-de-toulouse-lautrec',
    tier: 'medium',
    periodId: 'post-impressionism',
    wikiTitle: 'Henri de Toulouse-Lautrec',
    paintings: [
      'At the Moulin Rouge',
      'At the Moulin Rouge, The Dance',
      'Moulin Rouge: La Goulue',
      'Le Lit (Toulouse-Lautrec)',
      'Marcelle Lender',
      'La Toilette (Toulouse-Lautrec)',
      'Portrait of Vincent van Gogh (1887)',
      'The Englishman at the Moulin Rouge',
      "La Blanchisseuse (Toulouse-Lautrec)",
      "Count Alphonse de Toulouse-Lautrec Driving His Mail-Coach",
      "The Tightrope Dancer",
      "Portrait of Suzanne Valadon (Toulouse-Lautrec)",
      "At Grenelle, Absinthe Drinker",
      "The Hangover (Suzanne Valadon)",
    ],
  },

  // ---- Expressionism (all public domain — died before 1956) ----
  {
    id: 'edvard-munch',
    tier: 'large',
    periodId: 'expressionism',
    wikiTitle: 'Edvard Munch',
    paintings: [
      'The Scream',
      'Madonna (Munch)',
      'The Sick Child (Munch)',
      'The Dance of Life (Munch)',
      'Anxiety (Munch)',
      'Evening on Karl Johan',
      'The Kiss (Munch)',
      'Starry Night (Munch)',
      "Love and Pain (Munch)",
      "Melancholy (Munch)",
      "Jealousy (Munch)",
      "Inger on the Beach",
      "Puberty (Munch)",
      "Christmas in the Brothel",
      "Self-Portrait. Between the Clock and the Bed.",
      "Ashes (Munch)",
      "Caricature Portrait of Tulla Larsen",
      "Death and the Child",
      "Morning Yawn",
      "Self-Portrait with Cigarette",
    ],
  },
  {
    id: 'ernst-ludwig-kirchner',
    tier: 'medium',
    periodId: 'expressionism',
    wikiTitle: 'Ernst Ludwig Kirchner',
    paintings: [
      'Street, Berlin (Kirchner)',
      'Berlin Street Scene',
      'Self-Portrait as a Soldier',
      'Five Bathing Women at a Lake',
      'The Red Tower in Halle',
      'Portrait of Erna Schilling',
      'Archers (Kirchner)',
      'The Bridge near Wiesen',
      "Female Half-Length Nude with Hat",
      "Alpine Kitchen",
    ],
  },
  {
    id: 'franz-marc',
    tier: 'medium',
    periodId: 'expressionism',
    wikiTitle: 'Franz Marc',
    paintings: [
      'The Tower of Blue Horses',
      'Yellow Cow',
      'Fate of the Animals',
      'Blue Horse I',
      'The Foxes (Marc)',
      'Little Blue Horse',
      'Blue Horses',
      'Horses in Landscape',
      "Fox (Marc)",
      "Hut in Dachau Moors",
      "Indersdorf",
      "Two Women on the Hillside",
    ],
  },
  {
    id: 'egon-schiele',
    tier: 'small',
    periodId: 'expressionism',
    wikiTitle: 'Egon Schiele',
    paintings: [
      'Portrait of Wally',
      'Death and the Maiden (Schiele)',
      'The Family (Schiele)',
      'Dämmernde Stadt',
      "Portrait of Edith (the artist's wife)",
      'Seated Woman with Bent Knees',
      'Dead City III',
    ],
  },

  {
    id: 'wassily-kandinsky',
    tier: 'medium',
    periodId: 'expressionism',
    wikiTitle: 'Wassily Kandinsky',
    paintings: [
      'Composition VI',
      'Composition VII',
      'The Blue Rider (Kandinsky)',
      'Improvisation No. 30 (Cannons)',
      'Das Bunte Leben',
      'Landscape with Red Spots',
      'Auf Weiss II (Sur blanc II)',
      'Composition X',
      "Simple Complexity",
      "Upward (Kandinsky)",
      "Three Elements",
      "Ein Zentrum (A Centre)",
    ],
  },

  // ---- Surrealism (no major surrealist is PD — all flagged) ----
  {
    id: 'salvador-dali',
    tier: 'large',
    periodId: 'surrealism',
    wikiTitle: 'Salvador Dalí',
    allowNonFree: true,
    paintings: [
      'The Persistence of Memory',
      'Christ of Saint John of the Cross',
      'Dream Caused by the Flight of a Bee Around a Pomegranate a Second Before Awakening',
      'Soft Construction with Boiled Beans (Premonition of Civil War)',
      'Metamorphosis of Narcissus',
      'Swans Reflecting Elephants',
      'Crucifixion (Corpus Hypercubus)',
      'The Elephants',
      "The Great Masturbator",
      "The Face of War",
      "The Burning Giraffe",
      "Landscape Near Figueras",
      "Leda Atomica",
      "The Sacrament of the Last Supper",
      "The Temptation of St. Anthony (Dalí)",
      "The Basket of Bread",
      "The Disintegration of the Persistence of Memory",
      "Young Woman at a Window",
      "The Discovery of America by Christopher Columbus",
      "The Hallucinogenic Toreador",
    ],
  },
  {
    id: 'rene-magritte',
    tier: 'large',
    periodId: 'surrealism',
    wikiTitle: 'René Magritte',
    allowNonFree: true,
    paintings: [
      'The Treachery of Images',
      'The Son of Man',
      'The Empire of Light',
      'Golconda (Magritte)',
      'The Lovers (Magritte)',
      'Time Transfixed',
      'The False Mirror',
      'Not to Be Reproduced',
      "The Mysteries of the Horizon",
      "The Castle of the Pyrenees",
      "The Menaced Assassin",
      "The Portrait (Magritte)",
      "16th September (painting)",
      "Elective Affinities (painting)",
      "The Human Condition (Magritte)",
      "The Listening Room",
      "The Telescope (Magritte)",
      "On the Threshold of Liberty",
      "The Voice of Space",
      "The Secret Player",
    ],
  },
  {
    id: 'max-ernst',
    tier: 'medium',
    periodId: 'surrealism',
    wikiTitle: 'Max Ernst',
    allowNonFree: true,
    paintings: [
      'The Elephant Celebes',
      'The Temptation of Saint Anthony (Ernst)',
      'Forest and Dove',
      'The Hat Makes the Man',
      'Pietà or Revolution by Night',
      'Men Shall Know Nothing of This',
      'The Eye of Silence',
      'Aquis Submersus',
      "Napoleon in the Wilderness",
      "Little Machine Constructed by Minimax Dadamax in Person",
      "Murdering Airplane",
      "The Barbarians (painting)",
      "The Wood (Max Ernst)",
      "Trophy, Hypertrophied",
    ],
  },

  {
    id: 'joan-miro',
    tier: 'medium',
    periodId: 'surrealism',
    wikiTitle: 'Joan Miró',
    allowNonFree: true,
    paintings: [
      'The Farm (Miró)',
      'The Tilled Field',
      "The Harlequin's Carnival",
      'Dog Barking at the Moon',
      'The Birth of the World',
      'Still Life with Old Shoe',
      'Head of a Catalan Peasant',
      'Ciphers and Constellations, in Love with a Woman',
      "Constellations (Miró)",
      "Portrait of Vincent Nubiola",
      "Barcelona Series",
      "Metamorphosis (Miró)",
      "Hands Flying off Toward the Constellations",
      "The Navigator's Hope",
      "Man and Woman in Front of a Pile of Excrement",
    ],
  },
  // Tanguy died 1955: PD in the EU since 2026 but not the US, so Commons
  // hosting is spotty — only 3 documented painting articles exist; kept at 3.
  {
    id: 'yves-tanguy',
    tier: 'small',
    periodId: 'surrealism',
    wikiTitle: 'Yves Tanguy',
    allowNonFree: true,
    paintings: [
      'Mama, Papa is Wounded!',
      "At 4 O'Clock in the Summer, Hope",
      'The Palace of the Windowed Rocks',
    ],
  },

  // ---- Cubism ----
  {
    id: 'juan-gris',
    tier: 'medium',
    periodId: 'cubism',
    wikiTitle: 'Juan Gris',
    // Article lead image is an en.wiki-only Man Ray photo; use his Commons-hosted self-portrait.
    portraitFile: 'Juan Gris - 1912 - Self-portrait.jpg',
    paintings: [
      'Still Life with a Guitar',
      'The Breakfast',
      'Violin and Playing Cards on a Table',
      'Still Life with Checked Tablecloth',
      'Harlequin with a Guitar',
      'The Fruit Bowl',
      'Checkerboard and Playing Cards',
      'Juan Legua',
      "The Anisette Bottle",
      "Still Life with a Poem",
    ],
  },
  {
    id: 'robert-delaunay',
    tier: 'medium',
    periodId: 'cubism',
    wikiTitle: 'Robert Delaunay',
    paintings: [
      'Windows Open Simultaneously 1st Part, 3rd Motif',
      'Cardiff Team',
      'Champs de Mars: The Red Tower',
      'Portuguese Woman',
      'Homage to Blériot',
      'Windows (Delaunay series)',
      'Rhythms (Delaunay)',
      'Portrait of Tristan Tzara',
      "Eiffel Tower (Delaunay series)",
      "Still Life with a Parrot",
    ],
  },
  {
    id: 'albert-gleizes',
    tier: 'large',
    periodId: 'cubism',
    wikiTitle: 'Albert Gleizes',
    paintings: [
      'Man on a Balcony',
      'Portrait of Jacques Nayral',
      'Football Players',
      'Harvest Threshing',
      'Woman with Phlox',
      'Brooklyn Bridge (Gleizes)',
      'Woman with Animals',
      'The Bathers (Gleizes)',
      "Le Chemin, Paysage à Meudon",
      "Man in a Hammock",
      "Portrait of an Army Doctor",
      "The Publisher Eugène Figuière",
      "Woman with Black Glove",
      "Composition for \"Jazz\"",
      "Cubist Landscape",
      "Passy, Bridges of Paris",
      "The Banks of the Marne (Gleizes)",
      "The Hunt (Gleizes)",
      "The Tree (Gleizes)",
    ],
  },
  // Cubism retrofit: still under copyright — flagged for local personal use.
  {
    id: 'pablo-picasso',
    tier: 'large',
    periodId: 'cubism',
    wikiTitle: 'Pablo Picasso',
    allowNonFree: true,
    paintings: [
      "Les Demoiselles d'Avignon",
      'Guernica (Picasso)',
      'The Old Guitarist',
      'Three Musicians (Picasso)',
      'Girl with a Mandolin',
      'Ma Jolie (Picasso, New York)',
      'The Weeping Woman',
      'Family of Saltimbanques',
      "Garçon à la pipe",
      "Dora Maar au Chat",
      "Le Rêve (Picasso)",
      "Les Femmes d'Alger",
      "Nude, Green Leaves and Bust",
      "Massacre in Korea",
      "Picasso's Rose Period",
      "La Vie (painting)",
      "Le pigeon aux petits pois",
      "Portrait of Suzanne Bloch",
      "Femme aux Bras Croisés",
      "Girl on a Ball",
    ],
  },
  {
    id: 'georges-braque',
    tier: 'medium',
    periodId: 'cubism',
    wikiTitle: 'Georges Braque',
    allowNonFree: true,
    paintings: [
      "Houses at l'Estaque",
      "The Viaduct at L'Estaque",
      'Woman with a Mandolin',
      'Pitcher and Violin',
      'Fruit Dish',
      'The Guitar (painting)',
      'Mandora (painting)',
      'Still Life (Braque, 1911)',
      "Fishing Boats",
    ],
  },

  // Léger died 1955: PD-first per painting (EU PD since 2026; some pre-1930
  // works are PD-US), fair-use fallback for the rest.
  {
    id: 'fernand-leger',
    tier: 'small',
    periodId: 'cubism',
    wikiTitle: 'Fernand Léger',
    allowNonFree: true,
    paintings: [
      'The City (Léger)',
      'Woman with a Cat (Léger)',
      'The Tugboat (Léger)',
      'Composition with Three Figures',
      'Still Life with Candlestick',
      'Man and Woman (Léger)',
    ],
  },

  // ---- Abstract Expressionism (all under copyright — flagged) ----
  {
    id: 'jackson-pollock',
    tier: 'small',
    periodId: 'abstract-expressionism',
    wikiTitle: 'Jackson Pollock',
    allowNonFree: true,
    paintings: [
      'No. 5, 1948',
      'Autumn Rhythm (Number 30)',
      'Blue Poles',
      'One: Number 31, 1950',
      'Convergence (Pollock)',
      'Mural (1943)',
      'Number 17A',
      "Number 1, 1950 (Lavender Mist)",
      "Mural on Indian Red Ground",
    ],
  },
  {
    id: 'mark-rothko',
    tier: 'medium',
    periodId: 'abstract-expressionism',
    wikiTitle: 'Mark Rothko',
    allowNonFree: true,
    // article lead image is fair-use; Commons has Kanaga's 1949 portrait
    // released by the Brooklyn Museum with "no known restrictions"
    portraitFile: 'Consuelo Kanaga, Mark Rothko, Yorktown Heights, ca. 1949.jpg',
    paintings: [
      'No. 61 (Rust and Blue)',
      'Orange, Red, Yellow',
      'White Center (Yellow, Pink and Lavender on Rose)',
      'Black on Maroon',
      'No. 3/No. 13 (Magenta, Black, Green on Orange)',
      'Four Darks in Red',
      'No 1 (Royal Red and Blue)',
      'No. 10 (Rothko)',
      "Black in Deep Red",
      "No. 6 (Violet, Green and Red)",
      "Untitled (Rothko)",
      "No. 6 (Yellow, White, Blue over Yellow on Gray)",
      "Seagram murals",
    ],
  },
  {
    id: 'willem-de-kooning',
    tier: 'small',
    periodId: 'abstract-expressionism',
    wikiTitle: 'Willem de Kooning',
    allowNonFree: true,
    paintings: [
      'Woman I',
      'Woman III',
      'Interchange (de Kooning)',
      'Woman-Ochre',
      'Police Gazette (painting)',
      'Woman VI',
    ],
  },

  // ---- Pop Art (all under copyright — flagged) ----
  {
    id: 'andy-warhol',
    tier: 'large',
    periodId: 'pop-art',
    wikiTitle: 'Andy Warhol',
    allowNonFree: true,
    paintings: [
      "Campbell's Soup Cans",
      'Marilyn Diptych',
      'Shot Marilyns',
      'Eight Elvises',
      'Green Coca-Cola Bottles',
      'Gold Marilyn Monroe',
      'Triple Elvis',
      'Mao (Warhol)',
      "Silver Car Crash (Double Disaster)",
      "Camouflage Self-Portrait",
      "Ten Portraits of Jews of the Twentieth Century",
      "Ethel Scull 36 Times",
      "Suicide (Purple Jumping Man)",
      "Big Electric Chair",
      "Campbell's Soup II",
      "Green Car Crash",
      "129 Die in Jet!",
      "Cars (painting)",
      "Flowers (Warhol)",
      "Men in Her Life (painting)",
    ],
  },
  {
    id: 'roy-lichtenstein',
    tier: 'large',
    periodId: 'pop-art',
    wikiTitle: 'Roy Lichtenstein',
    allowNonFree: true,
    paintings: [
      'Whaam!',
      'Drowning Girl',
      'Look Mickey',
      'M-Maybe',
      'Oh, Jeff...I Love You, Too...But...',
      'In the Car',
      'Crying Girl',
      'Masterpiece (Lichtenstein)',
      "Grrrrrrrrrrr!!",
      "Girl in Mirror",
      "Girl with Ball",
      "I Can See the Whole Room...and There's Nobody in It!",
      "Torpedo...Los!",
      "As I Opened Fire",
      "Bedroom at Arles",
      "Takka Takka (Lichtenstein)",
      "Brattata",
      "Crak!",
      "Girl with Hair Ribbon",
      "Golf Ball",
    ],
  },
  {
    id: 'jasper-johns',
    tier: 'small',
    periodId: 'pop-art',
    wikiTitle: 'Jasper Johns',
    allowNonFree: true,
    paintings: [
      'Flag (painting)',
      'Three Flags',
      'Map (painting)',
      'White Flag (painting)',
      'Racing Thoughts (Jasper Johns)',
      'Slice (painting)',
    ],
  },

  // ---- Contemporary (all under copyright — flagged) ----
  {
    id: 'jean-michel-basquiat',
    tier: 'large',
    periodId: 'contemporary',
    wikiTitle: 'Jean-Michel Basquiat',
    allowNonFree: true,
    paintings: [
      'Untitled (1982 Basquiat skull painting)',
      'Hollywood Africans',
      'Irony of Negro Policeman',
      'Horn Players',
      'Dustheads',
      'Boy and Dog in a Johnnypump',
      'In This Case',
      'Dos Cabezas',
      "A Panel of Experts",
      "Gem Spa (Basquiat)",
      "La Hara",
      "Taxi, 45th/Broadway",
      "Untitled (Fishing)",
      "Untitled (Skull)",
      "Bird on Money",
      "Cadillac Moon",
      "Charles the First (Basquiat)",
      "Crown Hotel (Mona Lisa Black Background)",
      "Defacement (The Death of Michael Stewart)",
      "Donut Revenge",
    ],
  },
  {
    id: 'david-hockney',
    tier: 'medium',
    periodId: 'contemporary',
    wikiTitle: 'David Hockney',
    allowNonFree: true,
    paintings: [
      'A Bigger Splash',
      'Portrait of an Artist (Pool with Two Figures)',
      'Mr and Mrs Clark and Percy',
      'American Collectors (Fred and Marcia Weisman)',
      "Peter Getting Out of Nick's Pool",
      'Bigger Trees Near Warter',
      'Garrowby Hill (painting)',
      'We Two Boys Together Clinging',
      "Portrait of Sir David Webster",
      "The Splash",
    ],
  },
  // Gerhard Richter was dropped: en.wikipedia hosts no fair-use images for
  // nearly all his painting articles (1 of 7 survived), below the 4+ floor.
  {
    id: 'lucian-freud',
    tier: 'small',
    periodId: 'contemporary',
    wikiTitle: 'Lucian Freud',
    allowNonFree: true,
    paintings: [
      'Benefits Supervisor Sleeping',
      'Portrait of Elizabeth II (Freud)',
      'After Cézanne',
      'The Brigadier (painting)',
      'Portrait of Kitty',
      'Naked Child Laughing (painting)',
      'Head on a Green Sofa',
    ],
  },
  // Richter retry (round 4): most articles still have no image on en.wiki;
  // whatever sticks is kept, even a single work.
  {
    id: 'gerhard-richter',
    tier: 'small',
    periodId: 'contemporary',
    wikiTitle: 'Gerhard Richter',
    allowNonFree: true,
    paintings: [
      'Abstraktes Bild (809-1)',
      'Cathedral Square, Milan (painting)',
      'Birkenau (painting)',
      'Seascape (Slightly Cloudy)',
      '48 Portraits',
      'Wand (Wall)',
      '18. Oktober 1977',
    ],
  },
  // Bacon's median work year (~1971) sits just left of the Contemporary band —
  // honest to his dates; selection favors his later triptychs plus the icons.
  {
    id: 'francis-bacon',
    tier: 'large',
    periodId: 'contemporary',
    wikiTitle: 'Francis Bacon (artist)',
    allowNonFree: true,
    paintings: [
      'Three Studies for Figures at the Base of a Crucifixion',
      "Study after Velázquez's Portrait of Pope Innocent X",
      'Figure with Meat',
      'Three Studies for a Crucifixion',
      'In Memory of George Dyer',
      'Triptych–August 1972',
      'Triptych, May–June 1973',
      'Portrait of Michel Leiris (1976)',
      "Three Studies of Lucian Freud",
      "Fragment of a Crucifixion",
      "Head VI",
      "Painting 1946",
      "Head I",
      "Second Version of Triptych 1944",
      "Study for a Self-Portrait—Triptych, 1985–86",
      "Three Figures in a Room",
      "Three Studies for Self-Portrait (1979)",
      "Blood on the Floor (painting)",
      "Figure in a Landscape",
      "Head II",
    ],
  },
]
