// Curated source config for the data pipeline.
// Adding a period or artist later = adding an entry here and re-running `npm run fetch-data`.
// Painting titles are exact en.wikipedia article titles; the pipeline fails loudly on
// titles that don't resolve and rejects any image that is not hosted on Wikimedia
// Commons with a public-domain license.

export const periods = [
  // Keep this array in chronological order — timeline label rows cycle by order.
  {
    id: 'medieval-gothic',
    name: 'Medieval & Gothic',
    wikiTitle: 'Gothic art',
    start: 1200,
    end: 1400,
    color: '#8c6d46',
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    wikiTitle: 'Renaissance art',
    start: 1400,
    end: 1600,
    color: '#c9a227',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    wikiTitle: 'Baroque painting',
    start: 1600,
    end: 1750,
    color: '#a4443c',
  },
  {
    id: 'rococo',
    name: 'Rococo',
    wikiTitle: 'Rococo',
    start: 1720,
    end: 1780,
    color: '#d9a0b4',
  },
  {
    id: 'neoclassicism',
    name: 'Neoclassicism',
    wikiTitle: 'Neoclassicism',
    start: 1770,
    end: 1830,
    color: '#aab3bd',
  },
  {
    id: 'romanticism',
    name: 'Romanticism',
    wikiTitle: 'Romanticism',
    start: 1800,
    end: 1850,
    color: '#7e3b52',
  },
  {
    id: 'realism',
    name: 'Realism',
    wikiTitle: 'Realism (art movement)',
    start: 1848,
    end: 1880,
    color: '#6b7f57',
  },
  {
    id: 'impressionism',
    name: 'Impressionism',
    wikiTitle: 'Impressionism',
    start: 1860,
    end: 1886,
    color: '#5b8bd0',
  },
  {
    id: 'post-impressionism',
    name: 'Post-Impressionism',
    wikiTitle: 'Post-Impressionism',
    start: 1886,
    end: 1905,
    color: '#d0763b',
  },
  {
    id: 'expressionism',
    name: 'Expressionism',
    wikiTitle: 'Expressionism',
    start: 1905,
    end: 1933,
    color: '#d94f30',
  },
  {
    id: 'cubism',
    name: 'Cubism',
    wikiTitle: 'Cubism',
    start: 1907,
    end: 1922,
    color: '#7b6c8f',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    wikiTitle: 'Surrealism',
    start: 1924,
    end: 1955,
    color: '#3fa8a0',
  },
  {
    id: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    wikiTitle: 'Abstract expressionism',
    start: 1943,
    end: 1965,
    color: '#c24b6e',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    wikiTitle: 'Pop art',
    start: 1955,
    end: 1975,
    color: '#38b6e8',
  },
  {
    id: 'contemporary',
    name: 'Contemporary',
    wikiTitle: 'Contemporary art',
    start: 1975,
    end: 2020,
    color: '#9ba53d',
  },
]

export const artists = [
  // ---- Medieval & Gothic ----
  {
    id: 'giotto',
    periodId: 'medieval-gothic',
    wikiTitle: 'Giotto',
    paintings: [
      'Ognissanti Madonna',
      'Lamentation (The Mourning of Christ)',
      'Stefaneschi Triptych',
      'Badia Polyptych',
      'Saint Francis Receiving the Stigmata (Giotto)',
      'Padua Crucifix',
    ],
  },
  {
    id: 'cimabue',
    periodId: 'medieval-gothic',
    wikiTitle: 'Cimabue',
    paintings: [
      'Santa Trinita Maestà',
      'Maestà of Santa Maria dei Servi',
      'Gualino Madonna',
      'Castelfiorentino Madonna',
      'Maestà (Cimabue)',
      'The Mocking of Christ (Cimabue)',
    ],
  },
  {
    id: 'duccio',
    periodId: 'medieval-gothic',
    wikiTitle: 'Duccio',
    paintings: [
      'Maestà (Duccio)',
      'Rucellai Madonna',
      'Madonna and Child (Duccio, Metropolitan)',
      'Crevole Madonna',
      'Madonna with Child and Six Angels',
      'Madonna and Child with Saints Polyptych',
    ],
  },

  {
    id: 'fra-angelico',
    periodId: 'medieval-gothic',
    wikiTitle: 'Fra Angelico',
    paintings: [
      'Annunciation (Fra Angelico, San Marco)',
      'Annunciation of Cortona',
      'San Marco Altarpiece',
      'Coronation of the Virgin (Fra Angelico, Louvre)',
      'The Last Judgment (Fra Angelico, Florence)',
      'Deposition of Christ (Fra Angelico)',
      'Fiesole Altarpiece',
      'Madonna of Humility (Fra Angelico)',
    ],
  },
  {
    id: 'simone-martini',
    periodId: 'medieval-gothic',
    wikiTitle: 'Simone Martini',
    paintings: [
      'Annunciation with Saint Margaret and Saint Ansanus',
      'Maestà (Simone Martini)',
      'Guidoriccio da Fogliano at the Siege of Montemassi',
      'Saint Louis of Toulouse Crowning His Brother Robert of Anjou',
      'Blessed Agostino Novello Triptych',
      'Orsini Polyptych',
      'Saint Catherine of Alexandria Polyptych',
    ],
  },

  // ---- Renaissance ----
  {
    id: 'leonardo-da-vinci',
    periodId: 'renaissance',
    wikiTitle: 'Leonardo da Vinci',
    paintings: [
      'Mona Lisa',
      'The Last Supper (Leonardo)',
      'Lady with an Ermine',
      "Ginevra de' Benci",
      'Virgin of the Rocks',
      'Annunciation (Leonardo)',
      'Saint John the Baptist (Leonardo)',
      'La Belle Ferronnière',
    ],
  },
  {
    id: 'michelangelo',
    periodId: 'renaissance',
    wikiTitle: 'Michelangelo',
    paintings: [
      'The Creation of Adam',
      'The Last Judgment (Michelangelo)',
      'Doni Tondo',
      'The Entombment (Michelangelo)',
      'Manchester Madonna',
      'The Torment of Saint Anthony (Michelangelo)',
    ],
  },
  {
    id: 'raphael',
    periodId: 'renaissance',
    wikiTitle: 'Raphael',
    paintings: [
      'The School of Athens',
      'Sistine Madonna',
      'Transfiguration (Raphael)',
      'The Marriage of the Virgin (Raphael)',
      'Saint George and the Dragon (Raphael)',
      'La Fornarina',
      'Portrait of Baldassare Castiglione',
      'Madonna of the Goldfinch',
    ],
  },

  {
    id: 'titian',
    periodId: 'renaissance',
    wikiTitle: 'Titian',
    paintings: [
      'Venus of Urbino',
      'Bacchus and Ariadne',
      'Sacred and Profane Love',
      'Assumption of the Virgin (Titian)',
      'Diana and Actaeon (Titian)',
      'Equestrian Portrait of Charles V',
      'Pietà (Titian)',
      'Penitent Magdalene (Titian, 1550)',
    ],
  },
  {
    id: 'sandro-botticelli',
    periodId: 'renaissance',
    wikiTitle: 'Sandro Botticelli',
    paintings: [
      'The Birth of Venus',
      'Primavera (Botticelli)',
      'Venus and Mars (Botticelli)',
      'The Mystical Nativity',
      'Madonna of the Magnificat',
      'Pallas and the Centaur',
      'Adoration of the Magi (Botticelli, 1475)',
      'Cestello Annunciation',
    ],
  },
  {
    id: 'jan-van-eyck',
    periodId: 'renaissance',
    wikiTitle: 'Jan van Eyck',
    paintings: [
      'Arnolfini Portrait',
      'Ghent Altarpiece',
      'Madonna of Chancellor Rolin',
      'Madonna in the Church',
      'Virgin and Child with Canon van der Paele',
      'Annunciation (van Eyck, Washington)',
      'Dresden Triptych',
      'Lucca Madonna',
    ],
  },

  // ---- Baroque ----
  {
    id: 'caravaggio',
    periodId: 'baroque',
    wikiTitle: 'Caravaggio',
    paintings: [
      'The Calling of Saint Matthew',
      'Judith Beheading Holofernes (Caravaggio)',
      'David with the Head of Goliath (Caravaggio, Rome)',
      'Bacchus (Caravaggio)',
      'Basket of Fruit (Caravaggio)',
      'Supper at Emmaus (Caravaggio, London)',
      'The Entombment of Christ (Caravaggio)',
      'The Cardsharps',
    ],
  },
  {
    id: 'rembrandt',
    periodId: 'baroque',
    wikiTitle: 'Rembrandt',
    paintings: [
      'The Night Watch',
      'The Anatomy Lesson of Dr. Nicolaes Tulp',
      'The Storm on the Sea of Galilee',
      'The Jewish Bride',
      "Belshazzar's Feast (Rembrandt)",
      'The Return of the Prodigal Son (Rembrandt)',
      'Aristotle with a Bust of Homer',
      'Self-Portrait with Two Circles',
    ],
  },
  {
    id: 'johannes-vermeer',
    periodId: 'baroque',
    wikiTitle: 'Johannes Vermeer',
    paintings: [
      'Girl with a Pearl Earring',
      'The Milkmaid (Vermeer)',
      'View of Delft',
      'The Art of Painting',
      'The Astronomer (Vermeer)',
      'The Geographer',
      'The Little Street',
      'Girl Reading a Letter at an Open Window',
    ],
  },

  {
    id: 'peter-paul-rubens',
    periodId: 'baroque',
    wikiTitle: 'Peter Paul Rubens',
    paintings: [
      'The Descent from the Cross (Rubens, 1612–1614)',
      'The Elevation of the Cross (Rubens)',
      'Massacre of the Innocents (Rubens)',
      'Samson and Delilah (Rubens)',
      'The Garden of Love (Rubens)',
      "Daniel in the Lions' Den (Rubens)",
      'The Hippopotamus and Crocodile Hunt',
      'The Fall of the Damned',
    ],
  },
  {
    id: 'diego-velazquez',
    periodId: 'baroque',
    wikiTitle: 'Diego Velázquez',
    paintings: [
      'Las Meninas',
      'The Surrender of Breda',
      'Rokeby Venus',
      'Portrait of Innocent X',
      'The Triumph of Bacchus',
      'Apollo in the Forge of Vulcan',
      'Old Woman Frying Eggs',
      'The Waterseller of Seville',
    ],
  },
  {
    id: 'artemisia-gentileschi',
    periodId: 'baroque',
    wikiTitle: 'Artemisia Gentileschi',
    paintings: [
      'Judith Slaying Holofernes (Artemisia Gentileschi, Florence)',
      'Judith Slaying Holofernes (Artemisia Gentileschi, Naples)',
      'Self-Portrait as the Allegory of Painting',
      'Susanna and the Elders (Artemisia Gentileschi, Pommersfelden)',
      'Judith and Her Maidservant (Artemisia Gentileschi, Florence)',
      'Self-Portrait as Saint Catherine of Alexandria',
      'Lucretia (Artemisia Gentileschi, Milan)',
      'Danaë (Artemisia Gentileschi)',
    ],
  },

  // ---- Rococo ----
  {
    id: 'antoine-watteau',
    periodId: 'rococo',
    wikiTitle: 'Antoine Watteau',
    paintings: [
      'The Embarkation for Cythera',
      'Pierrot (Watteau)',
      "L'Enseigne de Gersaint",
      'Mezzetino (Watteau)',
      'The Embarrassing Proposal',
      'Fêtes Vénitiennes',
      "L'Indifférent",
      'The Two Cousins',
    ],
  },
  {
    id: 'francois-boucher',
    periodId: 'rococo',
    wikiTitle: 'François Boucher',
    paintings: [
      'The Toilet of Venus (Boucher)',
      'Portrait of Madame de Pompadour',
      'The Blonde Odalisque',
      'Lovers in a Park',
      'Pompadour at Her Toilette',
      'The Brunette Odalisque',
    ],
  },
  {
    id: 'jean-honore-fragonard',
    periodId: 'rococo',
    wikiTitle: 'Jean-Honoré Fragonard',
    paintings: [
      // article's lead image is a CC BY-SA re-photograph; use the PD-Art scan
      { title: 'The Swing (Fragonard)', imageFile: 'Jean-Honoré Fragonard - The Swing - Google Art Project.jpg' },
      'A Young Girl Reading',
      'The Bolt (Fragonard)',
      'The Stolen Kiss (painting)',
      'Blind Man\'s Buff (Fragonard, 1775–1780)',
      'The See-Saw (Fragonard, Madrid)',
      'The Music Lesson (Fragonard)',
      'Coresus Sacrificing Himself to Save Callirhoe',
    ],
  },

  {
    id: 'jean-baptiste-simeon-chardin',
    periodId: 'rococo',
    wikiTitle: 'Jean-Baptiste-Siméon Chardin',
    paintings: [
      'The Ray (Chardin)',
      'Saying Grace (Chardin)',
      'Soap Bubbles (Chardin)',
      'The House of Cards',
      'Boy with a Spinning-Top',
      'The Laundress (Chardin)',
      'Girl with a Racquet',
      'The Kitchen Maid (Chardin)',
    ],
  },

  // ---- Neoclassicism ----
  {
    id: 'jacques-louis-david',
    periodId: 'neoclassicism',
    wikiTitle: 'Jacques-Louis David',
    paintings: [
      'Oath of the Horatii',
      'The Death of Marat',
      'The Coronation of Napoleon',
      'Napoleon Crossing the Alps',
      'The Death of Socrates',
      'The Lictors Bring to Brutus the Bodies of His Sons',
      'Belisarius Begging for Alms',
      'Leonidas at Thermopylae',
    ],
  },
  {
    id: 'jean-auguste-dominique-ingres',
    periodId: 'neoclassicism',
    wikiTitle: 'Jean-Auguste-Dominique Ingres',
    paintings: [
      'Grande Odalisque',
      'The Turkish Bath',
      'The Valpinçon Bather',
      'The Apotheosis of Homer (Ingres)',
      'Jupiter and Thetis',
      'Oedipus and the Sphinx (Ingres)',
      'The Source (Ingres)',
      'Joan of Arc at the Coronation of Charles VII',
    ],
  },
  {
    id: 'elisabeth-vigee-le-brun',
    periodId: 'neoclassicism',
    wikiTitle: 'Élisabeth Vigée Le Brun',
    paintings: [
      'Self-Portrait in a Straw Hat',
      'Marie Antoinette and Her Children',
      'Marie Antoinette with a Rose',
      'Self-Portrait with Julie (Maternal Tenderness)',
      'Lady Hamilton as a Bacchante',
      'Portrait of Countess Golovina',
      'Madame de Staël as Corinne at Cape Miseno',
      'Portrait of Hubert Robert',
    ],
  },

  {
    id: 'honore-daumier',
    periodId: 'realism',
    wikiTitle: 'Honoré Daumier',
    paintings: [
      'The Third-Class Carriage',
      'Don Quixote and Sancho Panza (Daumier)',
      'The Laundress (Daumier)',
      'The Chess Players (Daumier)',
      'Ecce Homo (Daumier)',
      'The Emigrants (Daumier)',
      'The Republic (Daumier)',
      'Melodrama (Daumier)',
    ],
  },

  // ---- Impressionism ----
  {
    id: 'claude-monet',
    periodId: 'impressionism',
    wikiTitle: 'Claude Monet',
    paintings: [
      'Impression, Sunrise',
      'Woman with a Parasol – Madame Monet and Her Son',
      'The Magpie (Monet)',
      'Haystacks (Monet series)',
      'Rouen Cathedral (Monet series)',
      'Water Lilies (Monet series)',
      'Garden at Sainte-Adresse',
      'La Grenouillère (Monet)',
    ],
  },
  {
    id: 'pierre-auguste-renoir',
    periodId: 'impressionism',
    wikiTitle: 'Pierre-Auguste Renoir',
    paintings: [
      'Bal du moulin de la Galette',
      'Luncheon of the Boating Party',
      'Dance at Bougival',
      'Le Pont-Neuf (Renoir)',
      'The Swing (Renoir)',
      'Girls at the Piano',
      'Dance in the City',
      'Pink and Blue (Renoir)',
    ],
  },
  {
    id: 'edgar-degas',
    periodId: 'impressionism',
    wikiTitle: 'Edgar Degas',
    paintings: [
      "L'Absinthe",
      "The Ballet Class (Degas, Musée d'Orsay)",
      'The Dance Class (Degas, Metropolitan Museum of Art)',
      'A Cotton Office in New Orleans',
      'Miss La La at the Cirque Fernando',
      'Place de la Concorde (Degas)',
      'The Orchestra at the Opera',
      'Young Spartans Exercising',
    ],
  },

  // Mengs has no painting articles on en.wikipedia; West and Kauffman carry
  // the period's depth instead.
  {
    id: 'benjamin-west',
    periodId: 'neoclassicism',
    wikiTitle: 'Benjamin West',
    paintings: [
      'The Death of General Wolfe',
      'Death on the Pale Horse',
      'Benjamin Franklin Drawing Electricity from the Sky',
      "Penn's Treaty with the Indians",
      'The Death of Nelson (West painting)',
      'The Battle of La Hogue',
      'The Departure of Regulus',
      'Agrippina Landing at Brundisium with the Ashes of Germanicus',
    ],
  },
  {
    id: 'angelica-kauffman',
    periodId: 'neoclassicism',
    wikiTitle: 'Angelica Kauffman',
    portraitFile: 'Angelica Kauffmann, Self-Portrait as the Muse of Painting, 1787.jpg',
    paintings: [
      'Ariadne Abandoned by Theseus',
      'Penelope at Her Loom',
      'Cupid and the Graces',
      'Zeuxis Selecting Models for His Painting of Helen of Troy',
      'Virgil Reading the Aeneid to Augustus and Octavia',
      'The Sorrow of Telemachus',
      'Vortigern and Rowena (painting)',
      'Sappho Inspired by Love',
    ],
  },

  // ---- Romanticism ----
  {
    id: 'francisco-goya',
    periodId: 'romanticism',
    wikiTitle: 'Francisco Goya',
    paintings: [
      'The Third of May 1808',
      'The Second of May 1808',
      'Saturn Devouring His Son',
      'La maja desnuda',
      'La maja vestida',
      'Charles IV of Spain and His Family',
      "Witches' Sabbath (Goya, 1798)",
      'The Dog (Goya)',
    ],
  },
  {
    id: 'caspar-david-friedrich',
    periodId: 'romanticism',
    wikiTitle: 'Caspar David Friedrich',
    paintings: [
      'Wanderer above the Sea of Fog',
      'The Sea of Ice',
      'The Monk by the Sea',
      'The Abbey in the Oakwood',
      'Chalk Cliffs on Rügen',
      'The Stages of Life',
      'Two Men Contemplating the Moon',
      'Cross in the Mountains',
    ],
  },
  {
    id: 'eugene-delacroix',
    periodId: 'romanticism',
    wikiTitle: 'Eugène Delacroix',
    paintings: [
      'Liberty Leading the People',
      'The Death of Sardanapalus',
      'The Massacre at Chios',
      'The Barque of Dante',
      'Women of Algiers',
      'Entry of the Crusaders in Constantinople',
      'Greece on the Ruins of Missolonghi',
      'The Lion Hunt (Delacroix)',
    ],
  },
  {
    id: 'jmw-turner',
    periodId: 'romanticism',
    wikiTitle: 'J. M. W. Turner',
    paintings: [
      'The Fighting Temeraire',
      'Rain, Steam and Speed – The Great Western Railway',
      'The Slave Ship',
      "Snow Storm: Steam-Boat off a Harbour's Mouth",
      'The Burning of the Houses of Lords and Commons',
      'Dido building Carthage',
      'Ulysses Deriding Polyphemus',
      'Norham Castle, Sunrise',
    ],
  },

  {
    id: 'theodore-gericault',
    periodId: 'romanticism',
    wikiTitle: 'Théodore Géricault',
    paintings: [
      'The Raft of the Medusa',
      'The Charging Chasseur',
      'The Wounded Cuirassier',
      'The 1821 Derby at Epsom',
      'Portrait of a Kleptomaniac',
      'The Woman with a Gambling Mania',
      'Monomaniac of Envy',
      'Evening: Landscape with an Aqueduct',
    ],
  },
  {
    id: 'william-blake',
    periodId: 'romanticism',
    wikiTitle: 'William Blake',
    paintings: [
      'The Ghost of a Flea',
      'Newton (Blake)',
      'The Ancient of Days',
      'Nebuchadnezzar (Blake)',
      'The Great Red Dragon paintings',
    ],
  },

  // ---- Realism ----
  {
    id: 'gustave-courbet',
    periodId: 'realism',
    wikiTitle: 'Gustave Courbet',
    paintings: [
      'A Burial at Ornans',
      'The Stone Breakers',
      "The Painter's Studio",
      'Le Désespéré',
      'The Meeting (Courbet)',
      'Self-Portrait with a Black Dog',
      'The Wheat Sifters',
      'The Wave (Courbet)',
    ],
  },
  {
    id: 'jean-francois-millet',
    periodId: 'realism',
    wikiTitle: 'Jean-François Millet',
    paintings: [
      'The Gleaners',
      'The Angelus (painting)',
      'The Sower (Millet)',
      'Man with a Hoe',
      'Shepherdess with her Flock',
      'The Winnower (Millet)',
      'The Potato Harvest',
      'Starry Night (Millet)',
    ],
  },
  {
    id: 'edouard-manet',
    periodId: 'realism',
    wikiTitle: 'Édouard Manet',
    paintings: [
      'Olympia (Manet)',
      "Le Déjeuner sur l'herbe",
      'A Bar at the Folies-Bergère',
      'The Balcony (Manet)',
      'Music in the Tuileries',
      'The Railway',
      'The Old Musician',
      'The Execution of Emperor Maximilian',
    ],
  },

  {
    id: 'berthe-morisot',
    periodId: 'impressionism',
    wikiTitle: 'Berthe Morisot',
    paintings: [
      'The Cradle (Morisot)',
      "Summer's Day",
      'Eugène Manet on the Isle of Wight',
      'In the Dining Room',
      'Woman at her Toilette',
      'The Mother and Sister of the Artist',
      'The Harbor at Lorient',
      'The Psyche Mirror',
    ],
  },
  {
    id: 'mary-cassatt',
    periodId: 'impressionism',
    wikiTitle: 'Mary Cassatt',
    paintings: [
      "The Child's Bath",
      'The Boating Party',
      'Little Girl in a Blue Armchair',
      'The Cup of Tea',
      'In the Loge',
      'Lady at the Tea Table',
      'Young Mother Sewing (Mary Cassatt)',
      'The Tea',
    ],
  },
  {
    id: 'alfred-sisley',
    periodId: 'impressionism',
    wikiTitle: 'Alfred Sisley',
    paintings: [
      'The Bridge at Villeneuve-la-Garenne',
      'Flooding at Port-Marly',
      'Regatta at Molesey near Hampton Court',
      'The Forge at Marly-le-Roi',
      'Frost in Louveciennes',
      'Place du Chenil in Marly, Snow Effect',
      'The Seine at Bougival',
      'Under Hampton Court Bridge',
    ],
  },

  // ---- Post-Impressionism ----
  {
    id: 'vincent-van-gogh',
    periodId: 'post-impressionism',
    wikiTitle: 'Vincent van Gogh',
    paintings: [
      'The Starry Night',
      'Sunflowers (Van Gogh series)',
      'Café Terrace at Night',
      'The Potato Eaters',
      'Wheatfield with Crows',
      'Self-Portrait with Bandaged Ear',
      'Irises (painting)',
      'Almond Blossoms',
    ],
  },
  {
    id: 'paul-cezanne',
    periodId: 'post-impressionism',
    wikiTitle: 'Paul Cézanne',
    paintings: [
      'The Card Players',
      'The Basket of Apples',
      'Mont Sainte-Victoire (Cézanne)',
      'The Bathers (Cézanne)',
      'Pyramid of Skulls',
      "The Hanged Man's House",
      'A Modern Olympia',
      'Still Life with Apples and Oranges',
    ],
  },
  {
    id: 'paul-gauguin',
    periodId: 'post-impressionism',
    wikiTitle: 'Paul Gauguin',
    paintings: [
      'Where Do We Come From? What Are We? Where Are We Going?',
      'The Yellow Christ',
      'Vision After the Sermon',
      'When Will You Marry?',
      'Spirit of the Dead Watching',
      'Two Tahitian Women',
      'Ia Orana Maria',
      'Nevermore (Gauguin)',
    ],
  },

  {
    id: 'georges-seurat',
    periodId: 'post-impressionism',
    wikiTitle: 'Georges Seurat',
    paintings: [
      'A Sunday Afternoon on the Island of La Grande Jatte',
      'Bathers at Asnières',
      'The Circus (Seurat)',
      'Le Chahut',
      'Parade de cirque',
      'Models (painting)',
      'Young Woman Powdering Herself (Seurat)',
      'The Channel of Gravelines, Petit Fort Philippe',
    ],
  },
  {
    id: 'henri-de-toulouse-lautrec',
    periodId: 'post-impressionism',
    wikiTitle: 'Henri de Toulouse-Lautrec',
    paintings: [
      'At the Moulin Rouge',
      'At the Moulin Rouge, The Dance',
      'Moulin Rouge: La Goulue',
      'Le Lit (Toulouse-Lautrec)',
      'Marcelle Lender',
      'La Toilette (Toulouse-Lautrec)',
      'Portrait of Vincent van Gogh (1887)',
      'The Englishman at the Moulin Rouge',
    ],
  },

  // ---- Expressionism (all public domain — died before 1956) ----
  {
    id: 'edvard-munch',
    periodId: 'expressionism',
    wikiTitle: 'Edvard Munch',
    paintings: [
      'The Scream',
      'Madonna (Munch)',
      'The Sick Child (Munch)',
      'The Dance of Life (Munch)',
      'Anxiety (Munch)',
      'Evening on Karl Johan',
      'The Kiss (Munch)',
      'Starry Night (Munch)',
    ],
  },
  {
    id: 'ernst-ludwig-kirchner',
    periodId: 'expressionism',
    wikiTitle: 'Ernst Ludwig Kirchner',
    paintings: [
      'Street, Berlin (Kirchner)',
      'Berlin Street Scene',
      'Self-Portrait as a Soldier',
      'Five Bathing Women at a Lake',
      'The Red Tower in Halle',
      'Portrait of Erna Schilling',
      'Archers (Kirchner)',
      'The Bridge near Wiesen',
    ],
  },
  {
    id: 'franz-marc',
    periodId: 'expressionism',
    wikiTitle: 'Franz Marc',
    paintings: [
      'The Tower of Blue Horses',
      'Yellow Cow',
      'Fate of the Animals',
      'Blue Horse I',
      'The Foxes (Marc)',
      'Little Blue Horse',
      'Blue Horses',
      'Horses in Landscape',
    ],
  },
  {
    id: 'egon-schiele',
    periodId: 'expressionism',
    wikiTitle: 'Egon Schiele',
    paintings: [
      'Portrait of Wally',
      'Death and the Maiden (Schiele)',
      'The Family (Schiele)',
      'Dämmernde Stadt',
      "Portrait of Edith (the artist's wife)",
      'Seated Woman with Bent Knees',
      'Dead City III',
    ],
  },

  {
    id: 'wassily-kandinsky',
    periodId: 'expressionism',
    wikiTitle: 'Wassily Kandinsky',
    paintings: [
      'Composition VI',
      'Composition VII',
      'The Blue Rider (Kandinsky)',
      'Improvisation No. 30 (Cannons)',
      'Das Bunte Leben',
      'Landscape with Red Spots',
      'Auf Weiss II (Sur blanc II)',
      'Composition X',
    ],
  },

  // ---- Surrealism (no major surrealist is PD — all flagged) ----
  {
    id: 'salvador-dali',
    periodId: 'surrealism',
    wikiTitle: 'Salvador Dalí',
    allowNonFree: true,
    paintings: [
      'The Persistence of Memory',
      'Christ of Saint John of the Cross',
      'Dream Caused by the Flight of a Bee Around a Pomegranate a Second Before Awakening',
      'Soft Construction with Boiled Beans (Premonition of Civil War)',
      'Metamorphosis of Narcissus',
      'Swans Reflecting Elephants',
      'Crucifixion (Corpus Hypercubus)',
      'The Elephants',
    ],
  },
  {
    id: 'rene-magritte',
    periodId: 'surrealism',
    wikiTitle: 'René Magritte',
    allowNonFree: true,
    paintings: [
      'The Treachery of Images',
      'The Son of Man',
      'The Empire of Light',
      'Golconda (Magritte)',
      'The Lovers (Magritte)',
      'Time Transfixed',
      'The False Mirror',
      'Not to Be Reproduced',
    ],
  },
  {
    id: 'max-ernst',
    periodId: 'surrealism',
    wikiTitle: 'Max Ernst',
    allowNonFree: true,
    paintings: [
      'The Elephant Celebes',
      'The Temptation of Saint Anthony (Ernst)',
      'Forest and Dove',
      'The Hat Makes the Man',
      'Pietà or Revolution by Night',
      'Men Shall Know Nothing of This',
      'The Eye of Silence',
      'Aquis Submersus',
    ],
  },

  {
    id: 'joan-miro',
    periodId: 'surrealism',
    wikiTitle: 'Joan Miró',
    allowNonFree: true,
    paintings: [
      'The Farm (Miró)',
      'The Tilled Field',
      "The Harlequin's Carnival",
      'Dog Barking at the Moon',
      'The Birth of the World',
      'Still Life with Old Shoe',
      'Head of a Catalan Peasant',
      'Ciphers and Constellations, in Love with a Woman',
    ],
  },
  // Tanguy died 1955: PD in the EU since 2026 but not the US, so Commons
  // hosting is spotty — only 3 documented painting articles exist; kept at 3.
  {
    id: 'yves-tanguy',
    periodId: 'surrealism',
    wikiTitle: 'Yves Tanguy',
    allowNonFree: true,
    paintings: [
      'Mama, Papa is Wounded!',
      "At 4 O'Clock in the Summer, Hope",
      'The Palace of the Windowed Rocks',
    ],
  },

  // ---- Cubism ----
  {
    id: 'juan-gris',
    periodId: 'cubism',
    wikiTitle: 'Juan Gris',
    // Article lead image is an en.wiki-only Man Ray photo; use his Commons-hosted self-portrait.
    portraitFile: 'Juan Gris - 1912 - Self-portrait.jpg',
    paintings: [
      'Still Life with a Guitar',
      'The Breakfast',
      'Violin and Playing Cards on a Table',
      'Still Life with Checked Tablecloth',
      'Harlequin with a Guitar',
      'The Fruit Bowl',
      'Checkerboard and Playing Cards',
      'Juan Legua',
    ],
  },
  {
    id: 'robert-delaunay',
    periodId: 'cubism',
    wikiTitle: 'Robert Delaunay',
    paintings: [
      'Windows Open Simultaneously 1st Part, 3rd Motif',
      'Cardiff Team',
      'Champs de Mars: The Red Tower',
      'Portuguese Woman',
      'Homage to Blériot',
      'Windows (Delaunay series)',
      'Rhythms (Delaunay)',
      'Portrait of Tristan Tzara',
    ],
  },
  {
    id: 'albert-gleizes',
    periodId: 'cubism',
    wikiTitle: 'Albert Gleizes',
    paintings: [
      'Man on a Balcony',
      'Portrait of Jacques Nayral',
      'Football Players',
      'Harvest Threshing',
      'Woman with Phlox',
      'Brooklyn Bridge (Gleizes)',
      'Woman with Animals',
      'The Bathers (Gleizes)',
    ],
  },
  // Cubism retrofit: still under copyright — flagged for local personal use.
  {
    id: 'pablo-picasso',
    periodId: 'cubism',
    wikiTitle: 'Pablo Picasso',
    allowNonFree: true,
    paintings: [
      "Les Demoiselles d'Avignon",
      'Guernica (Picasso)',
      'The Old Guitarist',
      'Three Musicians (Picasso)',
      'Girl with a Mandolin',
      'Ma Jolie (Picasso, New York)',
      'The Weeping Woman',
      'Family of Saltimbanques',
    ],
  },
  {
    id: 'georges-braque',
    periodId: 'cubism',
    wikiTitle: 'Georges Braque',
    allowNonFree: true,
    paintings: [
      "Houses at l'Estaque",
      "The Viaduct at L'Estaque",
      'Woman with a Mandolin',
      'Pitcher and Violin',
      'Fruit Dish',
      'The Guitar (painting)',
      'Mandora (painting)',
      'Still Life (Braque, 1911)',
    ],
  },

  // Léger died 1955: PD-first per painting (EU PD since 2026; some pre-1930
  // works are PD-US), fair-use fallback for the rest.
  {
    id: 'fernand-leger',
    periodId: 'cubism',
    wikiTitle: 'Fernand Léger',
    allowNonFree: true,
    paintings: [
      'The City (Léger)',
      'Woman with a Cat (Léger)',
      'The Tugboat (Léger)',
      'Composition with Three Figures',
      'Still Life with Candlestick',
      'Man and Woman (Léger)',
    ],
  },

  // ---- Abstract Expressionism (all under copyright — flagged) ----
  {
    id: 'jackson-pollock',
    periodId: 'abstract-expressionism',
    wikiTitle: 'Jackson Pollock',
    allowNonFree: true,
    paintings: [
      'No. 5, 1948',
      'Autumn Rhythm (Number 30)',
      'Blue Poles',
      'One: Number 31, 1950',
      'Convergence (Pollock)',
      'Mural (1943)',
      'Number 17A',
    ],
  },
  {
    id: 'mark-rothko',
    periodId: 'abstract-expressionism',
    wikiTitle: 'Mark Rothko',
    allowNonFree: true,
    // article lead image is fair-use; Commons has Kanaga's 1949 portrait
    // released by the Brooklyn Museum with "no known restrictions"
    portraitFile: 'Consuelo Kanaga, Mark Rothko, Yorktown Heights, ca. 1949.jpg',
    paintings: [
      'No. 61 (Rust and Blue)',
      'Orange, Red, Yellow',
      'White Center (Yellow, Pink and Lavender on Rose)',
      'Black on Maroon',
      'No. 3/No. 13 (Magenta, Black, Green on Orange)',
      'Four Darks in Red',
      'No 1 (Royal Red and Blue)',
      'No. 10 (Rothko)',
    ],
  },
  {
    id: 'willem-de-kooning',
    periodId: 'abstract-expressionism',
    wikiTitle: 'Willem de Kooning',
    allowNonFree: true,
    paintings: [
      'Woman I',
      'Woman III',
      'Interchange (de Kooning)',
      'Woman-Ochre',
      'Police Gazette (painting)',
      'Woman VI',
    ],
  },

  // ---- Pop Art (all under copyright — flagged) ----
  {
    id: 'andy-warhol',
    periodId: 'pop-art',
    wikiTitle: 'Andy Warhol',
    allowNonFree: true,
    paintings: [
      "Campbell's Soup Cans",
      'Marilyn Diptych',
      'Shot Marilyns',
      'Eight Elvises',
      'Green Coca-Cola Bottles',
      'Gold Marilyn Monroe',
      'Triple Elvis',
      'Mao (Warhol)',
    ],
  },
  {
    id: 'roy-lichtenstein',
    periodId: 'pop-art',
    wikiTitle: 'Roy Lichtenstein',
    allowNonFree: true,
    paintings: [
      'Whaam!',
      'Drowning Girl',
      'Look Mickey',
      'M-Maybe',
      'Oh, Jeff...I Love You, Too...But...',
      'In the Car',
      'Crying Girl',
      'Masterpiece (Lichtenstein)',
    ],
  },
  {
    id: 'jasper-johns',
    periodId: 'pop-art',
    wikiTitle: 'Jasper Johns',
    allowNonFree: true,
    paintings: [
      'Flag (painting)',
      'Three Flags',
      'Map (painting)',
      'White Flag (painting)',
      'Racing Thoughts (Jasper Johns)',
      'Slice (painting)',
    ],
  },

  // ---- Contemporary (all under copyright — flagged) ----
  {
    id: 'jean-michel-basquiat',
    periodId: 'contemporary',
    wikiTitle: 'Jean-Michel Basquiat',
    allowNonFree: true,
    paintings: [
      'Untitled (1982 Basquiat skull painting)',
      'Hollywood Africans',
      'Irony of Negro Policeman',
      'Horn Players',
      'Dustheads',
      'Boy and Dog in a Johnnypump',
      'In This Case',
      'Dos Cabezas',
    ],
  },
  {
    id: 'david-hockney',
    periodId: 'contemporary',
    wikiTitle: 'David Hockney',
    allowNonFree: true,
    paintings: [
      'A Bigger Splash',
      'Portrait of an Artist (Pool with Two Figures)',
      'Mr and Mrs Clark and Percy',
      'American Collectors (Fred and Marcia Weisman)',
      "Peter Getting Out of Nick's Pool",
      'Bigger Trees Near Warter',
      'Garrowby Hill (painting)',
      'We Two Boys Together Clinging',
    ],
  },
  // Gerhard Richter was dropped: en.wikipedia hosts no fair-use images for
  // nearly all his painting articles (1 of 7 survived), below the 4+ floor.
  {
    id: 'lucian-freud',
    periodId: 'contemporary',
    wikiTitle: 'Lucian Freud',
    allowNonFree: true,
    paintings: [
      'Benefits Supervisor Sleeping',
      'Portrait of Elizabeth II (Freud)',
      'After Cézanne',
      'The Brigadier (painting)',
      'Portrait of Kitty',
      'Naked Child Laughing (painting)',
      'Head on a Green Sofa',
    ],
  },
  // Richter retry (round 4): most articles still have no image on en.wiki;
  // whatever sticks is kept, even a single work.
  {
    id: 'gerhard-richter',
    periodId: 'contemporary',
    wikiTitle: 'Gerhard Richter',
    allowNonFree: true,
    paintings: [
      'Abstraktes Bild (809-1)',
      'Cathedral Square, Milan (painting)',
      'Birkenau (painting)',
      'Seascape (Slightly Cloudy)',
      '48 Portraits',
      'Wand (Wall)',
      '18. Oktober 1977',
    ],
  },
  // Bacon's median work year (~1971) sits just left of the Contemporary band —
  // honest to his dates; selection favors his later triptychs plus the icons.
  {
    id: 'francis-bacon',
    periodId: 'contemporary',
    wikiTitle: 'Francis Bacon (artist)',
    allowNonFree: true,
    paintings: [
      'Three Studies for Figures at the Base of a Crucifixion',
      "Study after Velázquez's Portrait of Pope Innocent X",
      'Figure with Meat',
      'Three Studies for a Crucifixion',
      'In Memory of George Dyer',
      'Triptych–August 1972',
      'Triptych, May–June 1973',
      'Portrait of Michel Leiris (1976)',
    ],
  },
]
